Ext.define('FusionCharts.ext.FusionChartsHCCharts', {
  
});

/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @author FusionCharts Technologies LLP
 @version fusioncharts/3.3.0-release.18700
*/
FusionCharts(["private","modules.renderer.js-charts",function(){function Aa(a){for(var u={left:a.offsetLeft,top:a.offsetTop},a=a.offsetParent;a;)u.left+=a.offsetLeft,u.top+=a.offsetTop,a!==Ea.body&&a!==Ea.documentElement&&(u.left-=a.scrollLeft,u.top-=a.scrollTop),a=a.offsetParent;return u}function ea(a,u){for(var c=[],e=0,t=a.length;e<t;e++)c[e]=u.call(a[e],a[e],e,a);return c}function wa(a){a=(a||0)%ba;return a<0?ba+a:a}function Ba(a,u){return a<=X?a:u<=X?u:u>a?0:u}function la(a,u){var c=u-a;return c<
0?ba-c:c}function Ca(a,u,c,e,t){return U((u-c[1]-e.top)/t,a-c[0]-e.left)}function T(a,u,c,e,t,b,h,f,v,s){if(typeof a==="object")u=a.y,c=a.r,e=a.innerR,t=a.radiusYFactor,b=a.depth,h=a.seriesGroup,f=a.renderer,a=a.x;if(t<0||t>=1)t=0.6;a=a||0;u=u||0;c=c||1;e=e||0;b=b||0;this.renderer=f;this.hasOnePoint=v;this.use3DLighting=s;this.cx=a;this.cy=u;this.rx=c;this.ry=c*t;this.radiusYFactor=t;this.isDoughnut=e>0;this.innerRx=e;this.innerRy=e*t;this.depth=b;this.leftX=a-c;this.rightX=a+c;this.leftInnerX=a-
e;this.rightInnerX=a+e;this.depthY=u+b;this.topY=u-this.ry;this.bottomY=this.depthY+this.ry;this.bottomBorderGroup=f.group("bottom-border",h).attr({transform:"t0,"+b});this.outerBackGroup=f.group("outer-back-Side",h);this.slicingWallsBackGroup=f.group("slicingWalls-back-Side",h);this.innerBackGroup=f.group("inner-back-Side",h);this.innerFrontGroup=f.group("inner-front-Side",h);this.slicingWallsFrontGroup=f.group("slicingWalls-front-Side",h);this.topGroup=f.group("top-Side",h);this.moveCmdArr=[g];
this.lineCmdArr=[K];this.closeCmdArr=[r];this.centerPoint=[a,u];this.leftPoint=[this.leftX,u];this.topPoint=[a,this.topY];this.rightPoint=[this.rightX,u];this.bottomPoint=[a,u+this.ry];this.leftDepthPoint=[this.leftX,this.depthY];this.rightDepthPoint=[this.rightX,this.depthY];this.leftInnerPoint=[this.leftInnerX,u];this.rightInnerPoint=[this.rightInnerX,u];this.leftInnerDepthPoint=[this.leftInnerX,this.depthY];this.rightInnerDepthPoint=[this.rightInnerX,this.depthY];this.pointElemStore=[];this.slicingWallsArr=
[];a=[E,this.rx,this.ry,0,0,1,this.rightX,u];c=[E,this.rx,this.ry,0,0,1,this.leftX,u];e=[E,this.rx,this.ry,0,0,0,this.rightX,this.depthY];t=[E,this.rx,this.ry,0,0,0,this.leftX,this.depthY];b=[E,this.innerRx,this.innerRy,0,0,0,this.rightInnerX,u];u=[E,this.innerRx,this.innerRy,0,0,0,this.leftInnerX,u];h=[E,this.innerRx,this.innerRy,0,0,1,this.rightInnerX,this.depthY];f=[E,this.innerRx,this.innerRy,0,0,1,this.leftInnerX,this.depthY];this.isDoughnut?(this.topBorderPath=this.moveCmdArr.concat(this.leftPoint,
a,c,this.moveCmdArr,this.leftInnerPoint,b,u),this.topPath=this.moveCmdArr.concat(this.leftPoint,a,c,this.lineCmdArr,this.leftInnerPoint,b,u,this.closeCmdArr),this.innerFrontPath=this.moveCmdArr.concat(this.leftInnerPoint,b,this.lineCmdArr,this.rightInnerDepthPoint,f,this.closeCmdArr),this.innerBackPath=this.moveCmdArr.concat(this.rightInnerPoint,u,this.lineCmdArr,this.leftInnerDepthPoint,h,this.closeCmdArr)):this.topBorderPath=this.topPath=this.moveCmdArr.concat(this.leftPoint,a,c,this.closeCmdArr);
this.outerBackPath=this.moveCmdArr.concat(this.leftPoint,a,this.lineCmdArr,this.rightDepthPoint,t,this.closeCmdArr);this.outerFrontPath=this.moveCmdArr.concat(this.rightPoint,c,this.lineCmdArr,this.leftDepthPoint,e,this.closeCmdArr);this.clipPathforOuter=[g,this.leftX,this.topY,K,this.rightX,this.topY,this.rightX,this.bottomY,this.leftX,this.bottomY,r];this.clipPathforInner=[g,this.leftInnerX,this.topY,K,this.rightInnerX,this.topY,this.rightInnerX,this.bottomY,this.leftInnerX,this.bottomY,r];this.clipPathforNoClip=
[g,this.leftInnerX,this.topY,K,this.leftInnerX,this.bottomY,r]}var A=this,B=A.hcLib,xa=B.Raphael,Ea=window.document,C=B.BLANKSTRING,Ma=B.createTrendLine,p=B.pluck,fa=B.getValidValue,o=B.pluckNumber,O=B.defaultPaletteOptions,qa=B.getFirstValue,ya=B.getDefinedColor,ra=B.parseUnsafeString,Y=B.FC_CONFIG_STRING,ia=B.extend2,sa=B.getDashStyle,Q=B.toRaphaelColor,Fa=B.toPrecision,Ja=B.stubFN,S=B.hasSVG,b=B.each,d=B.hasTouch,l=d?10:3,i="rgba(192,192,192,"+(S?1.0E-6:0.0020)+")",n=document.documentMode===8?
"visible":"",g="M",K="L",E="A",r="Z",F=Math,V=F.sin,x=F.cos,U=F.atan2,I=F.round,ha=F.min,Pa=F.max,aa=F.abs,M=F.PI,na=F.floor,P=F.sqrt,Z=M/180,X=Math.PI,oa=X/2,ba=2*X,Qa=X+oa,Ta=B.graphics.getColumnColor,W=B.getFirstColor,Na=B.setLineHeight,Ka=B.pluckFontSize,Ga=B.getFirstAlpha,Da=B.graphics.getDarkColor,ta=B.graphics.getLightColor,ma=B.graphics.convertColor,Ha=B.COLOR_TRANSPARENT,i="rgba(192,192,192,"+(S?1.0E-6:0.0020)+")",Oa=B.POSITION_CENTER,Ua=B.POSITION_TOP,Ra=B.POSITION_BOTTOM,Va=B.POSITION_RIGHT,
Wa=B.POSITION_LEFT,k=B.chartAPI,Xa=B.titleSpaceManager,Ya=B.placeLegendBlockBottom,Za=B.placeLegendBlockRight,$a=B.graphics.mapSymbolName,Sa=k.singleseries,J=B.COMMASTRING,pa=B.ZEROSTRING,Ia=B.ONESTRING,ua=B.HUNDREDSTRING,La=B.PXSTRING,ab=B.COMMASPACE,ca=!/fusioncharts\.com$/i.test(location.hostname);k("column2d",{standaloneInit:!0,creditLabel:ca,rendererId:"cartesian"},k.column2dbase);k("column3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},k.column2d);
k("bar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:k.barbase},k.column2d);k("line",{standaloneInit:!0,creditLabel:ca,rendererId:"cartesian"},k.linebase);k("area2d",{standaloneInit:!0,creditLabel:ca,rendererId:"cartesian"},k.area2dbase);k("pie2d",{standaloneInit:!0,defaultSeriesType:"pie",defaultPlotShadow:1,sliceOnLegendClick:!0,rendererId:"pie",point:function(a,u,c,e,t){var b,h,f,v=t[Y],s=v.is3d,j,w,m,d,i=0,da=0,g=[],l=o(e.plotborderthickness,s?0.1:1),q=(f=o(e.use3dlighting,1))?o(e.radius3d,
e["3dradius"],90):100;j=o(e.showzeropies,1);var y=o(e.showpercentintooltip,1),k=o(e.showlabels,1),n=o(e.showvalues,1),E=o(e.showpercentvalues,e.showpercentagevalues,0),z=p(e.tooltipsepchar,e.hovercapsepchar,ab),D=p(e.labelsepchar,z),G=p(e.plotbordercolor,e.piebordercolor),K=t[Y].numberFormatter;w=c.length;var r,x,H=o(e.plotborderdashed,0),V=o(e.plotborderdashlen,5),F=o(e.plotborderdashgap,4);q>100&&(q=100);q<0&&(q=0);if(o(e.showlegend,0))t.legend.enabled=!0,t.legend.reversed=!Boolean(o(e.reverselegend,
0)),u.showInLegend=!0;for(a=0;a<w;a+=1)h=c[a],b=K.getCleanValue(h.value,!0),b===null||!j&&b===0||(g.push(h),i+=b);i===0&&(g=[]);u.enableRotation=g.length>1?o(e.enablerotation,1):0;u.is3D=s;u.use3DLighting=f;u.pieYScale=o(e.pieyscale,40);if(u.pieYScale<1)u.pieYScale=1;if(u.pieYScale>=100)u.pieYScale=80;u.pieYScale/=100;u.pieSliceDepth=o(e.pieslicedepth,15);if(u.pieSliceDepth<1)u.pieSliceDepth=1;u.managedPieSliceDepth=u.pieSliceDepth;for(a=g.length-1;a>=0;a-=1){h=g[a];b=K.getCleanValue(h.value,!0);
c=ra(p(h.label,h.name,C));j=p(h.color,t.colors[a%t.colors.length]);w=p(h.alpha,e.plotfillalpha,ua);m=p(h.bordercolor,G,ta(j,s?90:25)).split(J)[0];d=e.showplotborder==pa?pa:p(h.borderalpha,e.plotborderalpha,e.pieborderalpha,"80");f={opacity:Math.max(w,d)/100};if(r=Boolean(o(h.issliced,e.issliced,0)))v.preSliced=r;x=o(h.dashed,H)?sa(p(h.dashlen,V),p(h.dashgap,F),l):void 0;u.data.push({showInLegend:c!==C,y:b,name:c,shadow:f,toolText:ra(fa(h.tooltext)),color:this.getPointColor(j,w,q),_3dAlpha:w,borderColor:ma(m,
d),borderWidth:l,link:fa(h.link),sliced:r,dashStyle:x,doNotSlice:p(e.enableslicing,Ia)!=Ia});w=K.percentValue(b/i*100);m=K.dataLabels(b)||C;f=y===1?w:m;b=o(h.showlabel,k)===1?c:C;w=(j=o(h.showvalue,n))===1?E===1?w:m:C;h=fa(ra(h.displayvalue));w=h!==void 0&&j?h:w!==C&&b!==C?b+D+w:p(b,w);c=c!=C?c+z+f:f;h=u.data[da];h.displayValue=w;h.toolText=p(h.toolText,c);da+=1}u.valueTotal=i;t.legend.enabled=e.showlegend==Ia?!0:!1;u.startAngle=o(e.startingangle,0);t.chart.startingAngle=p(g.length>1?e.startingangle:
0,0);return u},getPointColor:function(a,u,c){var e,t,a=W(a),u=Ga(u);c<100&&S?(e=Math.floor((100-0.35*c)*85)/100,e=Da(a,e),t=Math.floor((100+c)*50)/100,a=ta(a,t),u={FCcolor:{color:a+J+e,alpha:u+J+u,ratio:c+",100",radialGradient:!0,gradientUnits:"userSpaceOnUse"}}):u={FCcolor:{color:a+J+a,alpha:u+J+u,ratio:"0,100"}};return u},configureAxis:function(a){var u=0,c=a[Y],e;a.plotOptions.series.dataLabels.style=a.xAxis.labels.style;a.plotOptions.series.dataLabels.color=a.xAxis.labels.style.color;delete c.x;
delete c[0];delete c[1];a.chart.plotBorderColor=a.chart.plotBackgroundColor=Ha;c=c.pieDATALabels=[];if(a.series.length===1&&(e=a.series[0].data)&&(u=a.series[0].data.length)>0&&a.plotOptions.series.dataLabels.enabled)for(;u--;)e[u]&&fa(e[u].displayValue)!==void 0&&c.push(e[u].displayValue)},spaceManager:function(a,u,c,e){var t=a[Y],b=t.is3d,h=this.name,f=t.smartLabel,v=o(t.pieDATALabels&&t.pieDATALabels.length,0),s=0,j=u.chart,w=o(j.managelabeloverflow,0),m=!t.preSliced&&j.enableslicing==pa&&(j.showlegend!=
Ia||j.interactivelegend==pa)?0:o(j.slicingdistance,20),d=o(j.pieradius,0),i=o(j.enablesmartlabels,j.enablesmartlabel,1),da=i?o(j.skipoverlaplabels,j.skipoverlaplabel,1):0,g=o(j.issmartlineslanted,1),l=o(j.labeldistance,j.nametbdistance,5),q=o(j.smartlabelclearance,5);c-=a.chart.marginRight+a.chart.marginLeft;var y=e-(a.chart.marginTop+a.chart.marginBottom),e=Math.min(y,c),k=p(j.smartlinecolor,O.plotFillColor[a.chart.paletteIndex]),n=o(j.smartlinealpha,100),E=o(j.smartlinethickness,1),z=a.plotOptions.series.dataLabels,
D=z.style,G=o(parseInt(D.lineHeight,10),12),K=a.series[0]||{},r=K.pieYScale,x=K.pieSliceDepth,e=d===0?e*0.15:d,H=0,H=2*e;z.connectorWidth=E;z.connectorPadding=o(j.connectorpadding,5);z.connectorColor=ma(k,n);y-=Xa(a,u,c,H<y?y-H:y/2);j.showlegend==Ia&&(p(j.legendposition,Ra).toLowerCase()!=Va?y-=Ya(a,u,c,y/2,!0):c-=Za(a,u,c/3,y,!0));f.setStyle(D);if(v!==1)for(;v--;)u=f.getOriSize(t.pieDATALabels[v]),s=Math.max(s,u.width);i&&(l=q+m);d===0&&(b?(y-=x,H=Math.min(c/2-s,(y/2-G)/r)-l):H=Math.min(c/2-s,y/
2-G)-l,H>=e?e=H:l=Math.max(l-(e-H),m));if(b&&(v=y-2*(e*r+G),x>v))K.managedPieSliceDepth=x-v;a.plotOptions.pie3d.slicedOffset=a.plotOptions.pie.slicedOffset=m;a.plotOptions.pie3d.size=a.plotOptions.pie.size=2*e;a.plotOptions.series.dataLabels.distance=l;a.plotOptions.series.dataLabels.isSmartLineSlanted=g;a.plotOptions.series.dataLabels.enableSmartLabels=i;a.plotOptions.series.dataLabels.skipOverlapLabels=da;a.plotOptions.series.dataLabels.manageLabelOverflow=w;if(h==="doughnut2d"||h==="doughnut3d")if(h=
o(j.doughnutradius,0),v=o(j.use3dlighting,1)?o(j.radius3d,j["3dradius"],50):100,v>100&&(v=100),v<0&&(v=0),j=h===0||h>=e?e/2:h,a.plotOptions.pie3d.innerSize=a.plotOptions.pie.innerSize=2*j,v>0&&S&&(j=parseInt(j/e*100,10),h=(100-j)/2,v=parseInt(h*v/100,10),j=j+J+v+J+2*(h-v)+J+v,a.series[0]&&a.series[0].data)){w=a.series[0].data;a=0;for(v=w.length;a<v;a+=1)if(h=w[a],h.color.FCcolor)h.color.FCcolor.ratio=j}},creditLabel:ca,eiMethods:{sliceDataItem:function(a){var u=this.jsVars.hcObj,c;if(u&&u.datasets&&
(c=u.datasets[0])&&c.data&&c.data[a]&&c.data[a].plot)return u.plotGraphicClick.call(c.data[a].plot)}}},Sa);k.pie2d.eiMethods.togglePieSlice=k.pie2d.eiMethods.sliceDataItem;k.pie2d.eiMethods.enableSlicingMovement=k.pie2d.eiMethods.enablelink=function(){A.raiseWarning(this,"1301081430","run","JSRenderer~enablelink()","Method deprecated.")};k("pie3d",{defaultSeriesType:"pie3d",rendererId:"pie3d",creditLabel:ca,getPointColor:function(a){return a},defaultPlotShadow:0},k.pie2d);k("doughnut2d",{getPointColor:function(a,
u,c){var e,t,a=W(a),u=Ga(u);c<100&&S?(e=Math.floor((85-0.2*(100-c))*100)/100,e=Da(a,e),t=Math.floor((100-0.5*c)*100)/100,a=ta(a,t),u={FCcolor:{color:e+J+a+J+a+J+e,alpha:u+J+u+J+u+J+u,radialGradient:!0,gradientUnits:"userSpaceOnUse",r:c}}):u={FCcolor:{color:a+J+a,alpha:u+J+u,ratio:"0,100"}};return u}},k.pie2d);k("doughnut3d",{defaultSeriesType:"pie3d",rendererId:"pie3d",getPointColor:k.pie3d,defaultPlotShadow:0},k.doughnut2d);k("pareto2d",{standaloneInit:!0,point:function(a,u,c,e,t){var b,h,f,v,s,
j,w,m,d,i,da,g,l,q,y,a=c.length,k=0;j={};l=t.chart.paletteIndex;var n=/3d$/.test(t.chart.defaultSeriesType),E=this.isBar,z=p(360-e.plotfillangle,90),D=o(e.plotborderthickness,1),G=t.chart.useRoundEdges,K=p(e.tooltipsepchar,", "),r=p(e.plotbordercolor,O.plotBorderColor[l]).split(J)[0],x=e.showplotborder==pa?pa:p(e.plotborderalpha,e.plotfillalpha,ua),H=t.xAxis,V=o(e.showcumulativeline,1),F=t[Y],L=F.axisGridManager,I=F.x,B=e.showtooltip!=pa,N=[],A=[],M=o(e.use3dlighting,1),P=t[Y].numberFormatter,U=o(e.showlinevalues,
e.showvalues),X=o(e.plotborderdashed,0),ha=o(e.plotborderdashlen,5),Z=o(e.plotborderdashgap,4),x=n?e.showplotborder?x:pa:x,r=n?p(e.plotbordercolor,"#FFFFFF"):r;for(g=h=0;h<a;h+=1)if(da=c[h],c[h].vline)L.addVline(H,da,g,t);else if(b=P.getCleanValue(da.value,!0),b!==null)da.value=b,N.push(da),g+=1;a=N.length;N.sort(function(a,c){return c.value-a.value});if(V)w=o(e.linedashed,0),q=W(p(e.linecolor,O.plotBorderColor[l])),h=p(e.linealpha,100),m=o(e.linedashlen,5),d=o(e.linedashgap,4),j=o(e.linethickness,
2),i={opacity:h/100},y=o(e.drawanchors,e.showanchors),y===void 0&&(y=h!=pa),f=o(e.anchorborderthickness,1),s=o(e.anchorsides,0),v=o(e.anchorradius,3),g=W(p(e.anchorbordercolor,q)),b=W(p(e.anchorbgcolor,O.anchorBgColor[l])),c=Ga(p(e.anchoralpha,ua)),da=Ga(p(e.anchorbgalpha,c))*c/100,w=w?sa(m,d,j):void 0,j={yAxis:1,data:[],type:"line",color:{FCcolor:{color:q,alpha:h}},lineWidth:j,marker:{enabled:y,fillColor:{FCcolor:{color:b,alpha:da}},lineColor:{FCcolor:{color:g,alpha:c}},lineWidth:f,radius:v,symbol:$a(s),
startAngle:p(e.anchorstartangle,90)}};else{if(e.showsecondarylimits!=="1")e.showsecondarylimits="0";if(e.showdivlinesecondaryvalue!=="1")e.showdivlinesecondaryvalue="0"}for(h=0;h<a;h+=1)da=N[h],b=o(da.showlabel,e.showlabels,1),c=ra(!b?C:qa(da.label,da.name)),L.addXaxisCat(H,h,h,c),k+=b=da.value,f=p(da.color,t.colors[h%t.colors.length])+J+(o(e.useplotgradientcolor,1)?ya(e.plotgradientcolor,O.plotGradientColor[l]):C),v=p(da.alpha,e.plotfillalpha,ua),s=p(da.ratio,e.plotfillratio),g={opacity:v/100},q=
p(da.alpha,x)+C,f=Ta(f,v,s,z,G,r,q,E,n),u.data.push(ia(this.getPointStub(da,b,c,t),{y:b,shadow:g,color:f[0],borderColor:f[1],borderWidth:D,use3DLighting:M,dashStyle:o(da.dashed,X)==1?sa(ha,Z,D):"",tooltipConstraint:this.tooltipConstraint})),this.pointValueWatcher(t,b),V&&A.push({value:k,dataLabel:c,tooltext:fa(da.tooltext)});I.catCount=a;F[1]||(F[1]={});F[1].stacking100Percent=!0;if(V&&k>0){h=0;for(a=A.length;h<a;h+=1)da=A[h],t=u.data[h],b=da.value/k*100,l=P.percentValue(b),e=t.displayValue!==C?l:
C,U==1&&(e=l),U==0&&(e=C),c=da.dataLabel,l=B?da.tooltext!==void 0?da.tooltext:(c!==C?c+K:C)+l:C,j.data.push({shadow:i,color:j.color,marker:j.marker,y:b,toolText:l,displayValue:e,link:t.link,dashStyle:w});return[u,j]}else return u},defaultSeriesType:"column",isDual:!0,creditLabel:ca,rendererId:"cartesian"},Sa);k("pareto3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0},k.pareto2d);k("mscolumn2d",{standaloneInit:!0,creditLabel:ca,rendererId:"cartesian"},k.mscolumn2dbase);k("mscolumn3d",
{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},k.mscolumn2d);k("msbar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:k.barbase},k.mscolumn2d);k("msbar3d",{defaultSeriesType:"bar3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},k.msbar2d);k("msline",{standaloneInit:!0,creditLabel:ca,rendererId:"cartesian"},k.mslinebase);k("msarea",{standaloneInit:!0,creditLabel:ca,rendererId:"cartesian"},k.msareabase);k("stackedcolumn2d",{isStacked:!0},k.mscolumn2d);
k("stackedcolumn3d",{isStacked:!0},k.mscolumn3d);k("stackedbar2d",{isStacked:!0},k.msbar2d);k("stackedbar3d",{isStacked:!0},k.msbar3d);k("stackedarea2d",{isStacked:!0,showSum:0},k.msarea);k("marimekko",{isValueAbs:!0,distributedColumns:!0,isStacked:!0,xAxisMinMaxSetter:Ja,postSeriesAddition:function(a,u){var c=a[Y],e=0,t=a.xAxis,b=100/c.marimekkoTotal,h=[],f=a.series,v=0,s=o(u.chart.plotborderthickness,1),j=a.chart.rotateValues,w=o(u.chart.rotatexaxispercentvalues,0),s=s*-0.5-(s%2+(w?0:4)),m=w?3:
0,d=j?270:0,i=ia({},a.plotOptions.series.dataLabels.style),l=parseInt(i.fontSize,10),g=c[0],k=g.stacking100Percent,q=!k,y=c.inCanvasStyle,n=this.numberFormatter,E=u.categories&&u.categories[0]&&u.categories[0].category||[],K=0,z=[],D,G,r,x,p,H,V,F;c.isXYPlot=!0;c.distributedColumns=!0;t.min=0;t.max=100;t.labels.enabled=!1;t.gridLineWidth=0;t.alternateGridColor=Ha;D=g.stack;u.chart.interactivelegend="0";g=0;for(G=a.xAxis.plotLines.length;g<G;g+=1)if(r=t.plotLines[g],r.isGrid)r.isCat=!0,h[r.value]=
r,r._hideLabel=!0;for(g=G=0;g<E.length;g+=1)E[g].vline||(K+=z[G]=n.getCleanValue(E[g].widthpercent||0),G+=1);t=D.floatedcolumn&&D.floatedcolumn[0]||[];if(K===100&&(t&&t.length)!==G)for(;G--;)t[G]||(t[G]={p:null});K=I(K);if(t){x=0;for(G=t.length;x<G;){F=t[x];e+=r=F&&F.p||0;H=K===100?z[x]:r*b;p=v+H/2;V=v+H;for(g=0;g<f.length;g+=1)if(E=a.series[g].data[x],E._FCX=v,E._FCW=H,k){if(E.y||E.y===0){D=E.y/r*100;E.y=D;if(E.showPercentValues)E.displayValue=this.numberFormatter.percentValue(D);if(E.showPercentInToolTip)E.toolText=
E.toolText+parseInt(D*100,10)/100+"%"}if(E.previousY||E.previousY===0)E.previousY=E.previousY/r*100}c.showStackTotal&&a.xAxis.plotLines.push({value:p,width:0,isVline:q,isTrend:!q,_isStackSum:1,zIndex:4,label:{align:Oa,textAlign:d,rotation:j?270:0,style:i,verticalAlign:Ua,offsetScale:q?r<0?F.n:F.p:void 0,offsetScaleIndex:0,y:r<0?j===270?4:l:-4,x:0,text:n.yAxis(Fa(r,10))}});if(h[x])h[x].value=p,h[x]._weight=H,h[x]._hideLabel=!1;x+=1;c.showXAxisPercentValues&&x<G&&a.xAxis.plotLines.push({value:V,width:0,
isVine:!0,label:{align:Oa,textAlign:w?Wa:Oa,rotation:w?270:0,backgroundColor:"#ffffff",backgroundOpacity:1,borderWidth:"1px",borderType:"solid",borderColor:y.color,style:{color:y.color,fontSize:y.fontSize,fontFamily:y.fontFamily,lineHeight:y.lineHeight},verticalAlign:Ra,y:s,x:m,text:this.numberFormatter.percentValue(V)},zIndex:5});v=V}}x=0;for(G=h.length;x<G;x+=1)if(h[x]&&h[x]._hideLabel)h[x].value=null},defaultSeriesType:"floatedcolumn"},k.stackedcolumn2d);k("msstackedcolumn2d",{series:function(a,
u,c){var e,b,d,h,f=u[Y],v=0,s,j;s=[];var w;u.legend.enabled=Boolean(o(a.chart.showlegend,1));if(a.dataset&&a.dataset.length>0){this.categoryAdder(a,u);e=0;for(b=a.dataset.length;e<b;e+=1)if(w=a.dataset[e].dataset){d=0;for(h=w.length;d<h;d+=1,v+=1)s={data:[],numColumns:b,columnPosition:e},j=Math.min(f.oriCatTmp.length,w[d].data&&w[d].data.length),s=this.point(c,s,w[d],a.chart,u,j,v,e),u.series.push(s)}if(this.isDual&&a.lineset&&a.lineset.length>0){d=0;for(h=a.lineset.length;d<h;d+=1,v+=1)s={data:[],
yAxis:1,type:"line"},c=a.lineset[d],j=Math.min(f.oriCatTmp.length,c.data&&c.data.length),u.series.push(k.msline.point.call(this,"msline",s,c,a.chart,u,j,v))}this.configureAxis(u,a);a.trendlines&&Ma(a.trendlines,u.yAxis,u[Y],!1,this.isBar)}},postSpaceManager:function(a,u,c){var f;var e=a[Y],b,d,h;if(this.isStacked&&e.showStackTotal&&(b=a.chart,f=(u=a.xAxis)&&u.plotLines,a=f,b=c-b.marginLeft-b.marginRight,c=e.plotSpacePercent,e=e[0].stack,e=e.column&&e.column.length,u=b/(u.max-u.min),u*((1-2*c)/e)>
50&&c==0.1)){u=50/u;c=a&&a.length;e=-((e-1)/2)*u;for(h=0;h<c;h+=1)if(d=a[h],d._isStackSum)b=d._catPosition+(e+u*d._stackIndex),d.value=b}}},k.stackedcolumn2d);k("mscombi2d",{standaloneInit:!0,creditLabel:ca,rendererId:"cartesian"},k.mscombibase);k("mscombi3d",{series:k.mscombi2d.series,eiMethods:function(a){var u={};b(a.split(","),function(a){u[a]=function(){A.raiseWarning(this,"1301081430","run","JSRenderer~"+a+"()","Method not applicable.")}});return u}("view2D,view3D,resetView,rotateView,getViewAngles,fitToStage")},
k.mscolumn3d);k("mscolumnline3d",{},k.mscombi3d);k("stackedcolumn2dline",{isStacked:!0,stack100percent:0},k.mscombi2d);k("stackedcolumn3dline",{isStacked:!0,stack100percent:0},k.mscombi3d);k("mscombidy2d",{isDual:!0,secondarySeriesType:void 0},k.mscombi2d);k("mscolumn3dlinedy",{isDual:!0,secondarySeriesType:"line"},k.mscolumnline3d);k("stackedcolumn3dlinedy",{isDual:!0,secondarySeriesType:"line"},k.stackedcolumn3dline);k("msstackedcolumn2dlinedy",{isDual:!0,stack100percent:0,secondarySeriesType:"line"},
k.msstackedcolumn2d);k("scrollcolumn2d",{postSeriesAddition:k.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},k.mscolumn2d);k("scrollline2d",{postSeriesAddition:k.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:75},k.msline);k("scrollarea2d",{postSeriesAddition:k.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:75},k.msarea);k("scrollstackedcolumn2d",
{postSeriesAddition:function(a,b,c,e){k.base.postSeriesAddition.call(this,a,b,c,e);k.scrollbase.postSeriesAddition.call(this,a,b,c,e)},canvasborderthickness:1,tooltipConstraint:"plot",avgScrollPointWidth:75},k.stackedcolumn2d);k("scrollcombi2d",{postSeriesAddition:k.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},k.mscombi2d);k("scrollcombidy2d",{postSeriesAddition:k.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,
avgScrollPointWidth:40},k.mscombidy2d);k("scatter",{standaloneInit:!0,defaultSeriesType:"scatter",defaultZeroPlaneHighlighted:!1,creditLabel:ca},k.scatterbase);k("bubble",{standaloneInit:!0,standaloneInut:!0,defaultSeriesType:"bubble",rendererId:"bubble",point:function(a,b,c,e,t,d,h){if(c.data){var f,v,s,j,w,m,i,g,l,n,E=!1,q,y,a=k[a],d=c.data,x=d.length,r=o(c.showvalues,t[Y].showValues);s=o(e.bubblescale,1);var K=p(e.negativecolor,"FF0000"),z=t.plotOptions.bubble,D=this.numberFormatter,G=o(c.showregressionline,
e.showregressionline,0);z.bubbleScale=s;b.name=fa(c.seriesname);if(o(c.includeinlegend)===0||b.name===void 0)b.showInLegend=!1;s=Boolean(o(c.drawanchors,c.showanchors,e.drawanchors,1));i=p(c.plotfillalpha,c.bubblefillalpha,e.plotfillalpha,ua);g=o(c.showplotborder,e.showplotborder,1);l=W(p(c.plotbordercolor,e.plotbordercolor,"666666"));f=p(c.plotborderthickness,e.plotborderthickness,1);n=p(c.plotborderalpha,e.plotborderalpha,"95");g=g==1?f:0;h=p(c.color,c.plotfillcolor,e.plotfillcolor,t.colors[h%t.colors.length]);
b.marker={enabled:s,fillColor:this.getPointColor(h,ua),lineColor:{FCcolor:{color:l,alpha:n}},lineWidth:g,symbol:"circle"};if(G){b.events={hide:this.hideRLine,show:this.showRLine};var V={sumX:0,sumY:0,sumXY:0,sumXsqure:0,sumYsqure:0,xValues:[],yValues:[]},F=o(c.showyonx,e.showyonx,1),I=W(p(c.regressionlinecolor,e.regressionlinecolor,h)),H=o(c.regressionlinethickness,e.regressionlinethickness,1);f=Ga(o(c.regressionlinealpha,e.regressionlinealpha,100));I=ma(I,f)}for(v=0;v<x;v+=1)if(j=d[v])if(f=D.getCleanValue(j.y),
q=D.getCleanValue(j.x),y=D.getCleanValue(j.z,!0),f===null)b.data.push({y:null,x:q});else{E=!0;w=W(p(j.color,j.z<0?K:h));m=p(j.alpha,i);j=a.getPointStub(j,f,q,t,c,r);w=o(e.use3dlighting)===0?w:a.getPointColor(w,m);if(y!==null)z.zMax=z.zMax>y?z.zMax:y,z.zMin=z.zMin<y?z.zMin:y;b.data.push({y:f,x:q,z:y,displayValue:j.displayValue,toolText:j.toolText,link:j.link,marker:{enabled:s,fillColor:w,lineColor:{FCcolor:{color:l,alpha:n}},lineWidth:g,symbol:"circle"}});this.pointValueWatcher(t,f,q,G&&V)}else b.data.push({y:null});
G&&(c={type:"line",color:I,showInLegend:!1,lineWidth:H,enableMouseTracking:!1,marker:{enabled:!1},data:this.getRegressionLineSeries(V,F,x),zIndex:0},b=[b,c])}if(!E)b.showInLegend=!1;return b},postSeriesAddition:function(a,b){a.chart.clipBubbles=o(b.chart.clipbubbles,1)},getPointStub:function(a,b,c,e,t,d){var e=e[Y],b=b===null?b:e.numberFormatter.dataLabels(b),h,f=e.tooltipSepChar;e.showTooltip?fa(a.tooltext)!==void 0?t=ra(a.tooltext):b===null?t=!1:(e.seriesNameInToolTip&&(h=p(t&&t.seriesname)),t=
h?h+f:C,t+=c?c+f:C,t+=b,t+=a.z?f+a.z:C):t=C;c=o(a.showvalue,d,e.showValues)?p(a.name,a.label)!==void 0?ra(p(a.name,a.label)):b:C;a=fa(a.link);return{displayValue:c,toolText:t,link:a}}},k.scatter);k("ssgrid",{standaloneInit:!0,defaultSeriesType:"ssgrid",rendererId:"ssgrid",chart:function(a,b){var u;var c=this.containerElement,e=this.dataObj,t=this.chartInstance,e=ia({},e);e.chart=e.chart||e.graph||{};delete e.graph;var d,h,f,v=0,s,j,w=[],m=e.chart,g=e.data,i=g&&g.length,e=this.smartLabel,l=this.numberFormatter,
n=c.offsetHeight,E=c.offsetWidth,q={},y=0,x=0,r=(m.palette>0&&m.palette<6?m.palette:o(this.paletteIndex,1))-1,c={_FCconf:{0:{stack:{}},1:{stack:{}},x:{stack:{}},noWrap:!1,marginLeftExtraSpace:0,marginRightExtraSpace:0,marginBottomExtraSpace:0,marginTopExtraSpace:0,marimekkoTotal:0},chart:{renderTo:c,ignoreHiddenSeries:!1,events:{},spacingTop:0,spacingRight:0,spacingBottom:0,spacingLeft:0,marginTop:0,marginRight:0,marginBottom:0,marginLeft:0,borderRadius:0,borderColor:"#000000",borderWidth:1,defaultSeriesType:"ssgrid",
style:{fontFamily:p(m.basefont,"Verdana"),fontSize:Ka(m.basefontsize,20)+La,color:p(m.basefontcolor,O.baseFontColor[r]).replace(/^#?([a-f0-9]+)/ig,"#$1")},plotBackgroundColor:Ha},labels:{smartLabel:e},colors:["AFD8F8","F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D","A186BE","CC6600","FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],credits:{href:"http://www.fusioncharts.com?BS=FCHSEvalMark",text:B.CREDIT_STRING,enabled:this.creditLabel},
legend:{enabled:!1},series:[],subtitle:{text:C},title:{text:C},tooltip:{enabled:!1},exporting:{buttons:{exportButton:{},printButton:{enabled:!1}}}},K=c[Y],z=c.colors,D=c.colors.length,G=s=h=y=0,x=v=j=0;f=t.jsVars.cfgStore;t=c.chart;Na(c.chart.style);t.events.click=this.linkClickFN;h=t.toolbar={button:{}};s=h.button;s.scale=o(m.toolbarbuttonscale,1.15);s.width=o(m.toolbarbuttonwidth,15);s.height=o(m.toolbarbuttonheight,15);s.radius=o(m.toolbarbuttonradius,2);s.spacing=o(m.toolbarbuttonspacing,5);s.fill=
ma(p(m.toolbarbuttoncolor,"ffffff"));s.labelFill=ma(p(m.toolbarlabelcolor,"cccccc"));s.symbolFill=ma(p(m.toolbarsymbolcolor,"ffffff"));s.hoverFill=ma(p(m.toolbarbuttonhovercolor,"ffffff"));s.stroke=ma(p(m.toolbarbuttonbordercolor,"bbbbbb"));s.symbolStroke=ma(p(m.toolbarsymbolbordercolor,"9a9a9a"));s.strokeWidth=o(m.toolbarbuttonborderthickness,1);s.symbolStrokeWidth=o(m.toolbarsymbolborderthickness,1);j=s.symbolPadding=o(m.toolbarsymbolpadding,5);s.symbolHPadding=o(m.toolbarsymbolhpadding,j);s.symbolVPadding=
o(m.toolbarsymbolvpadding,j);j=h.position=p(m.toolbarposition,"tr").toLowerCase();switch(j){case "tr":case "tl":case "br":case "bl":break;default:j="tr"}s=h.hAlign=(C+m.toolbarhalign).toLowerCase()==="left"?"l":j.charAt(1);u=h.vAlign=(C+m.toolbarvalign).toLowerCase()==="bottom"?"b":j.charAt(0),j=u;h.hDirection=o(m.toolbarhdirection,s==="r"?-1:1);h.vDirection=o(m.toolbarvdirection,j==="b"?-1:1);h.vMargin=o(m.toolbarvmargin,6);h.hMargin=o(m.toolbarhmargin,10);h.x=o(m.toolbarx,s==="l"?0:a);h.y=o(m.toolbary,
j==="t"?0:b);if(p(m.clickurl)!==void 0)t.link=m.clickurl,t.style.cursor="pointer";q.showPercentValues=o(f.showpercentvalues,m.showpercentvalues,0);q.numberItemsPerPage=p(f.numberitemsperpage,m.numberitemsperpage);q.showShadow=o(f.showshadow,m.showshadow,0);q.baseFont=p(f.basefont,m.basefont,"Verdana");d=Ka(f.basefontsize,m.basefontsize,10);q.baseFontSize=d+La;q.baseFontColor=W(p(f.basefontcolor,m.basefontcolor,O.baseFontColor[r]));q.alternateRowBgColor=W(p(f.alternaterowbgcolor,m.alternaterowbgcolor,
O.altHGridColor[r]));q.alternateRowBgAlpha=p(f.alternaterowbgalpha,m.alternaterowbgalpha,O.altHGridAlpha[r])+C;q.listRowDividerThickness=o(f.listrowdividerthickness,m.listrowdividerthickness,1);q.listRowDividerColor=W(p(f.listrowdividercolor,m.listrowdividercolor,O.borderColor[r]));q.listRowDividerAlpha=o(f.listrowdivideralpha,m.listrowdivideralpha,O.altHGridAlpha[r])+15+C;q.colorBoxWidth=o(f.colorboxwidth,m.colorboxwidth,8);q.colorBoxHeight=o(f.colorboxheight,m.colorboxheight,8);q.navButtonRadius=
o(f.navbuttonradius,m.navbuttonradius,7);q.navButtonColor=W(p(f.navbuttoncolor,m.navbuttoncolor,O.canvasBorderColor[r]));q.navButtonHoverColor=W(p(f.navbuttonhovercolor,m.navbuttonhovercolor,O.altHGridColor[r]));q.textVerticalPadding=o(f.textverticalpadding,m.textverticalpadding,3);q.navButtonPadding=o(f.navbuttonpadding,m.navbuttonpadding,5);q.colorBoxPadding=o(f.colorboxpadding,m.colorboxpadding,10);q.valueColumnPadding=o(f.valuecolumnpadding,m.valuecolumnpadding,10);q.nameColumnPadding=o(f.namecolumnpadding,
m.namecolumnpadding,5);q.borderThickness=o(f.borderthickness,m.borderthickness,1);q.borderColor=W(p(f.bordercolor,m.bordercolor,O.borderColor[r]));q.borderAlpha=p(f.borderalpha,m.borderalpha,O.borderAlpha[r])+C;q.bgColor=p(f.bgcolor,m.bgcolor,"FFFFFF");q.bgAlpha=p(f.bgalpha,m.bgalpha,ua);q.bgRatio=p(f.bgratio,m.bgratio,ua);q.bgAngle=p(f.bgangle,m.bgangle,pa);t.borderRadius=q.borderThickness/16;t.borderWidth=q.borderThickness;t.borderColor=Q({FCcolor:{color:q.borderColor,alpha:q.borderAlpha}});t.backgroundColor=
{FCcolor:{color:q.bgColor,alpha:q.bgAlpha,ratio:q.bgRatio,angle:q.bgAngle}};t.borderRadius=o(m.borderradius,0);f={fontFamily:q.baseFont,fontSize:q.baseFontSize,color:q.baseFontColor};Na(f);e.setStyle(f);for(v=0;v<i;v+=1)if(d=g[v],s=l.getCleanValue(d.value),j=ra(qa(d.label,d.name)),h=W(p(d.color,z[v%D])),p(d.alpha,m.plotfillalpha,ua),j!=C||s!=null)w.push({value:s,label:j,color:h}),y+=s,x+=1;for(v=0;v<x;v+=1)d=w[v],s=d.value,d.dataLabel=d.label,d.displayValue=q.showPercentValues?l.percentValue(s/y*
100):l.dataLabels(s),g=e.getOriSize(d.displayValue),G=Math.max(G,g.width+q.valueColumnPadding);q.numberItemsPerPage?q.numberItemsPerPage>=x?(q.numberItemsPerPage=x,s=n/q.numberItemsPerPage,h=x):(l=n,l-=2*(q.navButtonPadding+q.navButtonRadius),h=q.numberItemsPerPage,s=l/h):(y=parseInt(f.lineHeight,10),y+=2*q.textVerticalPadding,y=Math.max(y,q.colorBoxHeight),n/y>=x?(s=n/x,h=x):(l=n,l-=2*(q.navButtonPadding+q.navButtonRadius),h=Math.floor(l/y),s=l/h));j=E-q.colorBoxPadding-q.colorBoxWidth-q.nameColumnPadding-
G-q.valueColumnPadding;v=q.colorBoxPadding+q.colorBoxWidth+q.nameColumnPadding;l=p(m.basefont,"Verdana");g=Ka(m.basefontsize,10);r=p(m.basefontcolor,O.baseFontColor[r]);i=p(m.outcnvbasefont,l);d=Ka(m.outcnvbasefontsize,g);G=d+La;m=p(m.outcnvbasefontcolor,r).replace(/^#?([a-f0-9]+)/ig,"#$1");g+=La;r=r.replace(/^#?([a-f0-9]+)/ig,"#$1");K.trendStyle=K.outCanvasStyle={fontFamily:i,color:m,fontSize:G};Na(K.trendStyle);K.inCanvasStyle={fontFamily:l,fontSize:g,color:r};c.tooltip.style={fontFamily:l,fontSize:g,
lineHeight:void 0,color:r};c.tooltip.shadow=!1;t.height=n;t.width=E;t.rowHeight=s;t.labelX=v;t.colorBoxWidth=q.colorBoxWidth;t.colorBoxHeight=q.colorBoxHeight;t.colorBoxX=q.colorBoxPadding;t.valueX=q.colorBoxPadding+q.colorBoxWidth+q.nameColumnPadding+j+q.valueColumnPadding;t.valueColumnPadding=q.valueColumnPadding;t.textStyle=f;t.listRowDividerAttr={"stroke-width":q.listRowDividerThickness,stroke:{FCcolor:{color:q.listRowDividerColor,alpha:q.listRowDividerAlpha}}};t.alternateRowColor={FCcolor:{color:q.alternateRowBgColor,
alpha:q.alternateRowBgAlpha}};t.navButtonRadius=q.navButtonRadius;t.navButtonPadding=q.navButtonPadding;t.navButtonColor=q.navButtonColor;t.navButtonHoverColor=q.navButtonHoverColor;t.lineHeight=parseInt(f.lineHeight,10);m=[];n=0;q=!0;for(v=0;v<x&h!=0;v+=1)v%h==0&&(m.push({data:[],visible:q}),q=!1,n+=1),d=w[v],E=e.getSmartText(d.dataLabel,j,s),m[n-1].data.push({label:E.text,originalText:E.tooltext,displayValue:d.displayValue,y:d.value,color:d.color});c.series=m;k.base.parseExportOptions.call(this,
c);c.tooltip.enabled=!!c.exporting.enabled;return c},creditLabel:ca},k.base);k("renderer.bubble",{drawPlotBubble:function(a,b){var c=this,e=c.options,t=e.chart,d=e.plotOptions.series,h=c.paper,f=c.elements,v=a.items,s=a.graphics=a.graphics||[],j=c.xAxis[b.xAxis||0],w=c.yAxis[b.yAxis||0],m=a.data,g=(e.tooltip||{}).enabled!==!1,d=isNaN(+d.animation)&&d.animation.duration||d.animation*1E3,n=b.visible===!1?"hidden":"visible",e=e.plotOptions.bubble,r=e.zMax,e=e.bubbleScale,E=ha(c.canvasHeight,c.canvasWidth)/
8,r=P(r),k,q,y,x,K,p,z,D,G,V,F=c.layers,B=F.dataset=F.dataset||h.group("dataset-orphan");F.datalabels=F.datalabels||h.group("datalables").insertAfter(B);var F=F.tracker,H,R,B=B.bubble=B.bubble||h.group("bubble",B);t.clipBubbles&&!B.attrs["clip-rect"]&&B.attr({"clip-rect":f["clip-canvas"]});f=0;for(k=m.length;f<k;f+=1){q=m[f];G=V=R=null;D=q.marker;if(q.y!==null&&D&&D.enabled){y=q.link;t=q.toolText;x=o(q.x,f);K=q.y;z=w.getAxisPosition(K);p=j.getAxisPosition(x);G=P(q.z);H=I(G*E/r)*e;G=h.circle(p,z,0,
B).attr({fill:Q(D.fillColor),"stroke-width":D.lineWidth,stroke:Q(D.lineColor),visibility:n}).animate({r:H||0},d,"easeOut");if(y||g)H<l&&(H=l),V=h.circle(p,z,H,F).attr({cursor:y?"pointer":"",stroke:i,"stroke-width":D.lineWidth,fill:i,ishot:!!y,visibility:n}).tooltip(t).data("link",y).click(function(){var a=this.data("link");a&&c.linkClickFN.call({link:a},c)});v[f]={index:f,x:x,y:K,z:q.z,value:K,graphic:G,dataLabel:R,tracker:V};R=c.drawPlotLineLabel(a,b,f,p,z)}else v[f]={index:f,x:x,y:K};R&&s.push(R);
G&&s.push(G);V&&s.push(V)}a.visible=b.visible!==!1;return a}},k["renderer.cartesian"]);k("renderer.ssgrid",{drawGraph:function(){var a=this.options.series,b=this.elements,c=b.plots,e=a.length,t;if(!c)c=this.plots=this.plots||[],b.plots=c;this.drawSSGridNavButton();for(t=0;t<e;t++){if(!(b=c[t]))c.push(b={items:[],data:a[t].data});a[t].data&&a[t].data.length&&this.drawPlot(b,a[t])}e>1&&this.nenagitePage(0)},drawPlot:function(a){var b=a.data,c=this.paper,e=this.options.chart,t=e.colorBoxHeight,d=e.colorBoxWidth,
h=e.colorBoxX,f=e.labelX,v=e.valueX,s=e.rowHeight,j=e.width,w=e.listRowDividerAttr,m=w["stroke-width"],w=Q(w.stroke),l=m%2/2,i=e.textStyle,n=this.layers,n=n.dataset=n.dataset||c.group("dataset-orphan"),e=Q(e.alternateRowColor),a=a.items,r=0,x,q,y,k;if(!b||!b.length)b=[];w={stroke:w,"stroke-width":m};k=0;for(m=b.length;k<m;k+=1)if(y=b[k],q=y.y,x=a[k]={index:k,value:q,graphic:null,dataLabel:null,dataValue:null,alternateRow:null,listRowDivider:null,hot:null},!(q===null||q===void 0)){if(k%2===0)x.alternateRow=
c.rect(0,r,j,s,0,n).attr({fill:e,"stroke-width":0});q=I(r)+l;x.listRowDivider=c.path([g,0,q,K,j,q],n).attr(w);x.graphic=c.rect(h,r+s/2-t/2,d,t,0,n).attr({fill:y.color,"stroke-width":0,stroke:"#000000"});q=x.dataLabel=c.text().attr({text:y.label,title:y.originalText||"",x:f,y:r+s/2,fill:i.color,"text-anchor":"start"}).css(i);n.appendChild(q);x=x.dataValue=c.text().attr({text:y.displayValue,title:y.originalText||"",x:v,y:r+s/2,fill:i.color,"text-anchor":"start"}).css(i);n.appendChild(x);r+=s}q=I(r)+
l;c.path([g,0,q,K,j,q],n).attr(w)},drawSSGridNavButton:function(a){var a=this,b=a.paper,c=a.options,e=c.chart,t=c.series,d=e.navButtonColor,h=e.navButtonHoverColor,c=e.navButtonRadius,f=c*0.67,v=e.navButtonPadding+f+(t&&t[0].data&&t[0].data.length*e.rowHeight)+c*0.5,e=e.width-20,s,j,w;if(t.length>1){var m=a.naviigator=b.group("navigation");a.navElePrv=t=b.group(m);s=b.path([g,20,v,K,20+c+f,v-f,20+c,v,20+c+f,v+f,"Z"]).attr({fill:d,"stroke-width":0,cursor:"pointer"});t.appendChild(s);w=b.circle(20+
c,v,c).attr({fill:Ha,"stroke-width":0,cursor:"pointer"}).mouseover(function(){s.attr({fill:h,cursor:"pointer"})}).mouseout(function(){s.attr({fill:d})}).click(function(){a.nenagitePage(-1)});t.appendChild(w);a.navEleNxt=t=b.group(m);j=b.path([g,e,v,K,e-c-f,v-f,e-c,v,e-c-f,v+f,"Z"]).attr({fill:d,"stroke-width":0,cursor:"pointer"});t.appendChild(j);b=b.circle(e-c,v,c).attr({fill:Ha,"stroke-width":0,cursor:"pointer"}).mouseover(function(){j.attr({fill:h})}).mouseout(function(){j.attr({fill:d})}).click(function(){a.nenagitePage(1)});
t.appendChild(b)}},nenagitePage:function(a){var d=this.plots,c=d.length,a=(this.currentSeriesIndex||0)+(a||0),e;if(d[a]){for(e=c;e--;)b(d[e].items,function(a){a.graphic&&a.graphic.hide();a.dataLabel&&a.dataLabel.hide();a.dataValue&&a.dataValue.hide();a.alternateRow&&a.alternateRow.hide();a.listRowDivider&&a.listRowDivider.hide()});b(d[a].items,function(a){a.graphic&&a.graphic.show();a.dataLabel&&a.dataLabel.show();a.dataValue&&a.dataValue.show();a.alternateRow&&a.alternateRow.show();a.listRowDivider&&
a.listRowDivider.show()});this.currentSeriesIndex=a;a===0?this.navElePrv.hide():this.navElePrv.show();a===c-1?this.navEleNxt.hide():this.navEleNxt.show()}}},k["renderer.root"]);T.prototype={getArcPath:function(a,b,c,e,d,g,h,f,v,s){return c==d&&e==g?[]:[E,h,f,0,s,v,d,g]},parseColor:function(a,b){var c,e,d,g,h,f=b/2,v,s,j,w;this.use3DLighting?(c=Da(a,80),e=Da(a,75),d=ta(a,85),g=ta(a,70),h=ta(a,40)):(c=Da(a,90),e=Da(a,87),d=ta(a,93),g=ta(a,87),h=ta(a,80));v=e+J+d+J+g+J+d+J+e;j=b+J+b+J+b+J+b+J+b;s=e+
J+a+J+d+J+a+J+e;w=f+J+f+J+f+J+f+J+f;return{frontOuter:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:v,alpha:j,angle:0,ratio:"0,25,5,5,65"}},backOuter:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:e+J+a+J+h+J+a+J+e,alpha:w,angle:0,ratio:"0,62,8,8,22"}},frontInner:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:s,alpha:w,angle:0,ratio:"0,25,5,5,65"}},backInner:{FCcolor:{gradientUnits:"objectBoundingBox",x1:0,y1:0,x2:1,y2:0,color:v,
alpha:j,angle:0,ratio:"0,62,8,8,22"}},top:S?{FCcolor:{gradientUnits:"objectBoundingBox",radialGradient:!0,cx:0.3,cy:0.95,r:1,color:g+J+d+J+e,alpha:b+J+b+J+b,ratio:"0,10,90"}}:{FCcolor:{gradientUnits:"objectBoundingBox",color:g+J+g+J+d+J+e,alpha:b+J+b+J+b+J+b,angle:-72,ratio:"0,8,15,77"}},bottom:Q(ma(a,f)),startSlice:Q(ma(c,b)),endSlice:Q(ma(c,b))}},rotate:function(a){if(!this.hasOnePoint){for(var b=this.pointElemStore,c=0,e=b.length,d;c<e;c+=1)d=b[c],d=d._confObject,d.start+=a,d.end+=a,this.updateSliceConf(d);
this.refreshDrawing()}},refreshDrawing:function(){return function(){var a=this.slicingWallsArr,b=0,c,e=a.length,d,g,h,f,v=this.slicingWallsFrontGroup,s=this.slicingWallsBackGroup;a:{var j=a[0]&&a[0]._conf.index,w,m;f=j<=X;d=1;for(c=a.length;d<c;d+=1)if(m=a[d]._conf.index,w=m<=X,w!=f||m<j)break a;d=0}for(;b<e;b+=1,d+=1)d===e&&(d=0),c=a[d],f=c._conf.index,f<oa?v.appendChild(c):f<=X?(g?c.insertBefore(g):v.appendChild(c),g=c):f<Qa?(h?c.insertBefore(h):s.appendChild(c),h=c):s.appendChild(c)}}(),updateSliceConf:function(a,
b){var c=this.getArcPath,e=a.start,d=a.end,i=wa(e),h=wa(d),f,v,s,j,w,m,l,n,k,o,p,q,y,F,I,B,z=this.cx,D=this.cy,G=this.rx,A=this.ry,J=G+2,M=A+2,H=this.innerRx,R=this.innerRy,P=this.depth,L=this.depthY,U=a.elements,va,N,ga,C;f=x(i);v=V(i);s=x(h);j=V(h);w=z+G*f;m=D+A*v;l=z+J*f;n=D+M*v;va=m+P;N=z+G*s;ga=D+A*j;k=z+J*s;o=D+M*j;C=ga+P;this.isDoughnut?(p=z+H*f,q=D+R*v,I=q+P,y=z+H*s,F=D+R*j,B=F+P,a.startSlice=[g,w,m,K,w,va,p,I,p,q,r],a.endSlice=[g,N,ga,K,N,C,y,B,y,F,r]):(a.startSlice=[g,w,m,K,w,va,z,L,z,D,
r],a.endSlice=[g,N,ga,K,N,C,z,L,z,D,r]);if(S){a&&a.clipTopPath?(a.clipTopPath[1]=l,a.clipTopPath[2]=n,a.clipTopPath[9]=k,a.clipTopPath[10]=o):a.clipTopPath=[g,l,n,E,J,M,0,0,1,k,o,K,this.cx,this.cy,r];a.clipOuterFrontPath1=this.clipPathforNoClip;if(e!=d){if(i>h)if(i<X){if(a.clipOuterFrontPath1=[g,this.leftX,this.topY,K,w,this.topY,w,this.bottomY,this.leftX,this.bottomY,r],a.clipOuterFrontPath=[g,N,this.topY,K,this.rightX,this.topY,this.rightX,this.bottomY,N,this.bottomY,r],a.clipOuterBackPath=this.clipPathforOuter,
this.isDoughnut)a.clipInnerBackPath=this.clipPathforInner,a.clipInnerFrontPath=[g,this.leftInnerX,this.topY,K,p,this.topY,p,this.bottomY,this.leftInnerX,this.bottomY,r,g,y,this.topY,K,this.rightInnerX,this.topY,this.rightInnerX,this.bottomY,y,this.bottomY,r]}else if(h>X){if(a.clipOuterFrontPath=this.clipPathforOuter,a.clipOuterBackPath=[g,this.rightX,this.topY,K,w,this.topY,w,this.bottomY,this.rightX,this.bottomY,r,g,N,this.topY,K,this.leftX,this.topY,this.leftX,this.bottomY,N,this.bottomY,r],this.isDoughnut)a.clipInnerBackPath=
[g,this.rightInnerX,this.topY,K,p,this.topY,p,this.bottomY,this.rightInnerX,this.bottomY,r,g,y,this.topY,K,this.leftInnerX,this.topY,this.leftInnerX,this.bottomY,y,this.bottomY,r],a.clipInnerFrontPath=this.clipPathforInner}else{if(a.clipOuterFrontPath=[g,this.rightX,this.topY,K,N,this.topY,N,this.bottomY,this.rightX,this.bottomY,r],a.clipOuterBackPath=[g,this.rightX,this.topY,K,w,this.topY,w,this.bottomY,this.rightX,this.bottomY,r],this.isDoughnut)a.clipInnerBackPath=[g,this.rightInnerX,this.topY,
K,p,this.topY,p,this.bottomY,this.rightInnerX,this.bottomY,r],a.clipInnerFrontPath=[g,this.rightInnerX,this.topY,K,y,this.topY,y,this.bottomY,this.rightInnerX,this.bottomY,r]}else if(i<X)if(h>X){if(a.clipOuterFrontPath=[g,w,this.topY,K,this.leftX,this.topY,this.leftX,this.bottomY,w,this.bottomY,r],a.clipOuterBackPath=[g,N,this.topY,K,this.leftX,this.topY,this.leftX,this.bottomY,N,this.bottomY,r],this.isDoughnut)a.clipInnerBackPath=[g,y,this.topY,K,this.leftInnerX,this.topY,this.leftInnerX,this.bottomY,
y,this.bottomY,r],a.clipInnerFrontPath=[g,p,this.topY,K,this.leftInnerX,this.topY,this.leftInnerX,this.bottomY,p,this.bottomY,r]}else{if(a.clipOuterFrontPath=[g,w,this.topY,K,N,this.topY,N,this.bottomY,w,this.bottomY,r],a.clipOuterBackPath=this.clipPathforNoClip,this.isDoughnut)a.clipInnerBackPath=this.clipPathforNoClip,a.clipInnerFrontPath=[g,p,this.topY,K,y,this.topY,y,this.bottomY,p,this.bottomY,r]}else if(a.clipOuterFrontPath=this.clipPathforNoClip,a.clipOuterBackPath=[g,w,this.topY,K,N,this.topY,
N,this.bottomY,w,this.bottomY,r],this.isDoughnut)a.clipInnerBackPath=[g,p,this.topY,K,y,this.topY,y,this.bottomY,p,this.bottomY,r],a.clipInnerFrontPath=this.clipPathforNoClip;c=la(i,h);a.clipTopPath[7]=c>X?1:0}else a.clipOuterFrontPath=a.clipOuterBackPath=a.clipInnerBackPath=a.clipInnerFrontPath=this.clipPathforNoClip;if(!b){a.elements.startSlice._conf.index=i;a.elements.endSlice._conf.index=h;a.elements.frontOuter._conf.index=Ba(h,i);if(a.elements.frontOuter1)a.elements.frontOuter1._conf.index=i,
a.elements.frontOuter1.attr({"clip-path":a.clipOuterFrontPath1});a.thisElement.attr({"clip-path":a.clipTopPath});a.elements.bottom.attr({"clip-path":a.clipTopPath});a.elements.bottomBorder.attr({"clip-path":a.clipTopPath});a.elements.topBorder.attr({"clip-path":a.clipTopPath});a.elements.frontOuter.attr({"clip-path":a.clipOuterFrontPath});a.elements.backOuter.attr({"clip-path":a.clipOuterBackPath});this.isDoughnut&&(a.elements.backInner.attr({"clip-path":a.clipInnerBackPath}),a.elements.frontInner.attr({"clip-path":a.clipInnerFrontPath}));
this.hasOnePoint?(a.elements.startSlice.hide(),a.elements.endSlice.hide()):(a.elements.startSlice.attr({path:a.startSlice}).show(),a.elements.endSlice.attr({path:a.endSlice}).show())}}else{f=this.moveCmdArr;v=this.lineCmdArr;s=this.closeCmdArr;var ha=this.centerPoint;j=this.leftPoint;l=this.topPoint;n=this.rightPoint;k=this.bottomPoint;var Z=this.leftDepthPoint,ba=this.rightDepthPoint;o=this.leftInnerPoint;J=this.rightInnerPoint;M=this.leftInnerDepthPoint;P=this.rightInnerDepthPoint;a.outerFrontPath1=
[];if(e!=d){if(i>h?i<X?(e=c(z,D,w,m,this.leftX,D,G,A,1,0),d=c(z,D,this.leftX,D,this.rightX,D,G,A,1,0),ga=c(z,D,this.rightX,D,N,ga,G,A,1,0),a.outerBackPath=f.concat(j,d,v,ba,c(z,L,this.rightX,L,this.leftX,L,G,A,0,0),s),a.outerFrontPath1=f.concat([w,m],e,v,Z,c(z,L,this.leftX,L,w,va,G,A,0,0),s),a.outerFrontPath=f.concat(n,ga,v,[N,C],c(z,L,N,C,this.rightX,L,G,A,0,0),s),a.topBorderPath=f.concat([w,m],e,d,ga),this.isDoughnut?(w=c(z,D,y,F,this.rightInnerX,D,H,R,0,0),m=c(z,D,this.rightInnerX,D,this.leftInnerX,
D,H,R,0,0),q=c(z,D,this.leftInnerX,D,p,q,H,R,0,0),a.innerBackPath=f.concat(J,m,v,M,c(z,L,this.leftInnerX,L,this.rightInnerX,L,H,R,1,0),s),a.innerFrontPath=f.concat(o,q,v,[p,I],c(z,L,p,I,this.leftInnerX,L,H,R,1,0),s,f,[y,F],w,v,P,c(z,L,this.rightInnerX,L,y,B,H,R,1,0),s),a.topPath=a.topBorderPath.concat(v,[y,F],w,m,q,s),a.topBorderPath=a.topBorderPath.concat(f,[y,F],w,m,q)):a.topPath=a.topBorderPath.concat(v,ha,s)):h>X?(e=c(z,D,w,m,this.rightX,D,G,A,1,0),d=c(z,D,this.rightX,D,this.leftX,D,G,A,1,0),
ga=c(z,D,this.leftX,D,N,ga,G,A,1,0),a.outerFrontPath=f.concat(n,d,v,Z,c(z,L,this.leftX,L,this.rightX,L,G,A,0,0),s),a.outerBackPath=f.concat([w,m],e,v,ba,c(z,L,this.rightX,L,w,va,G,A,0,0),s,f,j,ga,v,[N,C],c(z,L,N,C,this.leftX,L,G,A,0,0),s),a.topBorderPath=f.concat([w,m],e,d,ga),this.isDoughnut?(w=c(z,D,y,F,this.leftInnerX,D,H,R,0,0),m=c(z,D,this.leftInnerX,D,this.rightInnerX,D,H,R,0,0),q=c(z,D,this.rightInnerX,D,p,q,H,R,0,0),a.innerFrontPath=f.concat(o,m,v,P,c(z,L,this.rightInnerX,L,this.leftInnerX,
L,H,R,1,0),s),a.innerBackPath=f.concat(J,q,v,[p,I],c(z,L,p,I,this.rightInnerX,L,H,R,1,0),s,f,[y,F],w,v,M,c(z,L,this.leftInnerX,L,y,B,H,R,1,0),s),a.topPath=a.topBorderPath.concat(v,[y,F],w,m,q,s),a.topBorderPath=a.topBorderPath.concat(f,[y,F],w,m,q)):a.topPath=a.topBorderPath.concat(v,ha,s)):(e=c(z,D,w,m,this.rightX,D,G,A,1,0),d=c(z,D,this.rightX,D,N,ga,G,A,1,0),a.outerFrontPath=f.concat(n,d,v,[N,C],c(z,L,N,C,this.rightX,L,G,A,0,0),s),a.outerBackPath=f.concat([w,m],e,v,ba,c(z,L,this.rightX,L,w,va,
G,A,0,0),s),a.topBorderPath=f.concat([w,m],e,d),this.isDoughnut?(w=c(z,D,y,F,this.rightInnerX,D,H,R,0,0),m=c(z,D,this.rightInnerX,D,p,q,H,R,0,0),a.innerFrontPath=f.concat([y,F],w,v,P,c(z,L,this.rightInnerX,L,y,B,H,R,1,0),s),a.innerBackPath=f.concat(J,m,v,[p,I],c(z,L,p,I,this.rightInnerX,L,H,R,1,0),s),a.topPath=a.topBorderPath.concat(v,[y,F],w,m,s),a.topBorderPath=a.topBorderPath.concat(f,[y,F],w,m)):a.topPath=a.topBorderPath.concat(v,ha,s)):i<X?h>X?(e=c(z,D,w,m,this.leftX,D,G,A,1,0),d=c(z,D,this.leftX,
D,N,ga,G,A,1,0),a.outerBackPath=f.concat(j,d,v,[N,C],c(z,L,N,C,this.leftX,L,G,A,0,0),s),a.outerFrontPath=f.concat([w,m],e,v,Z,c(z,L,this.leftX,L,w,va,G,A,0,0),s),a.topBorderPath=f.concat([w,m],e,d),this.isDoughnut?(w=c(z,D,y,F,this.leftInnerX,D,H,R,0,0),m=c(z,D,this.leftInnerX,D,p,q,H,R,0,0),a.innerBackPath=f.concat([y,F],w,v,M,c(z,L,this.leftInnerX,L,y,B,H,R,1,0),s),a.innerFrontPath=f.concat(o,m,v,[p,I],c(z,L,p,I,this.leftInnerX,L,H,R,1,0),s),a.topPath=a.topBorderPath.concat(v,[y,F],w,m,s),a.topBorderPath=
a.topBorderPath.concat(f,[y,F],w,m)):a.topPath=a.topBorderPath.concat(v,ha,s)):(e=c(z,D,w,m,N,ga,G,A,1,0),a.outerBackPath=f.concat([w,m]),a.topBorderPath=a.outerBackPath.concat(e),a.outerFrontPath=a.topBorderPath.concat(v,[N,C],c(z,L,N,C,w,va,G,A,0,0),s),this.isDoughnut?(w=c(z,D,y,F,p,q,H,R,0,0),a.innerBackPath=f.concat([y,F]),a.topPath=a.topBorderPath.concat(v,[y,F],w,s),a.topBorderPath=a.topBorderPath.concat(f,[y,F],w),a.innerFrontPath=a.innerBackPath.concat(w,v,[p,I],c(z,L,p,I,y,B,H,R,1,0),s)):
a.topPath=a.topBorderPath.concat(v,ha,s)):(e=c(z,D,w,m,N,ga,G,A,1,0),a.outerFrontPath=f.concat([w,m]),a.topBorderPath=a.outerFrontPath.concat(e),a.outerBackPath=a.topBorderPath.concat(v,[N,C],c(z,L,N,C,w,va,G,A,0,0),s),this.isDoughnut?(w=c(z,D,y,F,p,q,H,R,0,0),a.innerFrontPath=f.concat([y,F]),a.topPath=a.topBorderPath.concat(v,[y,F],w,s),a.topBorderPath=a.topBorderPath.concat(a.innerFrontPath,w),a.innerBackPath=a.innerFrontPath.concat(w,v,[p,I],c(z,L,p,I,y,B,H,R,1,0),s)):a.topPath=a.topBorderPath.concat(v,
ha,s)),e=f.concat(j,v,n),w=f.concat(l,v,k),a.topPath=a.topPath.concat(e,w),a.outerFrontPath=a.outerFrontPath.concat(e),a.outerFrontPath1=a.outerFrontPath1.concat(e),a.outerBackPath=a.outerBackPath.concat(e),this.isDoughnut)w=f.concat(o,v,J),a.innerFrontPath=a.innerFrontPath.concat(w),a.innerBackPath=a.innerBackPath.concat(w)}else if(a.topPath=a.outerFrontPath=a.outerBackPath=[],this.isDoughnut)a.innerFrontPath=a.innerBackPath=[];if(!b){a.elements.startSlice._conf.index=i;a.elements.endSlice._conf.index=
h;a.elements.frontOuter._conf.index=Ba(h,i);if(a.elements.frontOuter1)a.elements.frontOuter1._conf.index=i,U.frontOuter1.attr({path:a.outerFrontPath1});a.thisElement.attr({path:a.topPath});U.topBorder.attr({path:a.topBorderPath});U.bottom.attr({path:a.topPath});U.bottomBorder.attr({path:a.topBorderPath});U.frontOuter.attr({path:a.outerFrontPath});U.backOuter.attr({path:a.outerBackPath});this.isDoughnut&&(U.frontInner.attr({path:a.innerFrontPath}),U.backInner.attr({path:a.innerBackPath}));this.hasOnePoint?
(a.elements.startSlice.hide(),a.elements.endSlice.hide()):(a.elements.startSlice.attr({path:a.startSlice}).show(),a.elements.endSlice.attr({path:a.endSlice}).show())}}},createSlice:function(){var a={stroke:!0,strokeWidth:!0,"stroke-width":!0,dashstyle:!0,"stroke-dasharray":!0,translateX:!0,translateY:!0,"stroke-opacity":!0,transform:!0,fill:!0,opacity:!0,ishot:!0,start:!0,end:!0},b=function(c,b){var e,d,j=this,t=j._confObject,m,u=t.elements,g,i,l=t.pie3DManager;typeof c==="string"&&b!==void 0&&b!==
null&&(e=c,c={},c[e]=b);if(!c||typeof c==="string")j=j._attr(c);else{if(c.cx!==void 0)c.start=c.cx;if(c.cy!==void 0)c.end=c.cy;for(e in c)if(d=c[e],a[e])if(t[e]=d,e==="ishot"){m={};m[e]=d;for(g in u)u[g].attr(m);j._attr(m)}else if(e==="transform"){for(g in u)u[g].attr({transform:c[e]});j._attr({transform:c[e]})}else if(e==="stroke"||e==="strokeWidth"||e==="stroke-width"||e==="dashstyle"||e==="stroke-dasharray")m={},m[e]=d,u.topBorder.attr(m),u.startSlice.attr(m),u.endSlice.attr(m),u.bottomBorder.attr(m);
else{if(e!=="fill"&&(e==="start"||e==="end"))i=!0}else j._attr(e,d);i&&(l.updateSliceConf(t),l.refreshDrawing())}return j},c=function(a,c,b,e){var d=this._confObject.elements,u;for(u in d)if(b)d[u].drag(c,b,e);else d[u].on(a,c);return b?this.drag(c,b,e):this._on(a,c)},e=function(){var a=this._confObject.elements,c;for(c in a)a[c].hide();return this._hide()},t=function(){var a=this._confObject.elements,c;for(c in a)a[c].show();return this._show()},g=function(){var a=this._confObject,c=a.elements,b;
for(b in c)c[b].destroy();S&&(a.clipTop.destroy(),a.clipOuterFront.destroy(),a.clipOuterBack.destroy(),a.clipOuterFront1&&a.clipOuterFront1.destroy(),a.clipInnerFront&&a.clipInnerFront.destroy(),a.clipInnerBack&&a.clipInnerBack.destroy());return this._destroy()};return function(a,f,v,s,j,i,m,l){var n=this.renderer,v=this.parseColor(v,s),f={start:a,end:f,elements:{},pie3DManager:this,topPath:this.topPath,topBorderPath:this.topBorderPath,outerFrontPath:this.outerFrontPath,outerFrontPath1:this.outerFrontPath,
outerBackPath:this.outerBackPath,innerFrontPath:this.innerFrontPath,innerBackPath:this.innerBackPath},s=this.slicingWallsArr,k=f.elements,r;this.updateSliceConf(f,!0);S&&!d?(a=n.group(this.topGroup),n.path(f.topPath,a).attr({fill:Q(v.top),"stroke-width":0})):a=n.path(f.topPath,this.topGroup).attr({fill:Q(v.top),"stroke-width":0});k.topBorder=n.path(f.topBorderPath,this.topGroup).attr({stroke:j,"stroke-width":i});k.bottom=n.path(f.topPath,this.bottomBorderGroup).attr({fill:Q(v.bottom),"stroke-width":0});
k.bottomBorder=n.path(f.topBorderPath,this.bottomBorderGroup).attr({stroke:j,"stroke-width":i});S&&!d?(k.frontOuter=n.group(this.slicingWallsFrontGroup),n.path(f.outerFrontPath,k.frontOuter).attr({fill:Q(v.frontOuter),"stroke-width":0})):k.frontOuter=n.path(f.outerFrontPath,this.slicingWallsFrontGroup).attr({fill:Q(v.frontOuter),"stroke-width":0});k.backOuter=n.path(f.outerBackPath,this.outerBackGroup).attr({fill:Q(v.backOuter),"stroke-width":0});k.startSlice=n.path(f.startSlice,this.slicingWallsFrontGroup).attr({fill:Q(v.startSlice),
stroke:j,"stroke-width":i});k.endSlice=n.path(f.endSlice,this.slicingWallsFrontGroup).attr({fill:Q(v.endSlice),stroke:j,"stroke-width":i});j=wa(f.start);i=wa(f.end);if(la(j,i)>X){if(k.frontOuter1=n.path(f.outerFrontPath1,this.slicingWallsFrontGroup).attr({fill:Q(v.frontOuter),"stroke-width":0}),s.push(k.startSlice,k.frontOuter1,k.frontOuter,k.endSlice),k.frontOuter1._conf={index:j,isStart:0.5,pIndex:m},S)f.clipOuterFront1=f.clipOuterFrontPath1,k.frontOuter1.attr({"clip-path":f.clipOuterFront1})}else s.push(k.startSlice,
k.frontOuter,k.endSlice);k.frontOuter._conf={index:Ba(i,j),isStart:0.5,pIndex:m};k.startSlice._conf={index:j,isStart:0,pIndex:m};k.endSlice._conf={index:i,isStart:1,pIndex:m};this.hasOnePoint&&(k.startSlice.hide(),k.endSlice.hide());if(this.isDoughnut)k.frontInner=n.path(f.innerFrontPath,this.innerFrontGroup).attr({fill:Q(v.frontInner),"stroke-width":0}),S&&!d?(k.backInner=n.group(this.innerBackGroup),n.path(f.innerBackPath,k.backInner).attr({fill:Q(v.backInner),"stroke-width":0})):k.backInner=n.path(f.innerBackPath,
this.innerBackGroup).attr({fill:Q(v.backInner),"stroke-width":0});if(l!==void 0){for(r in k)k[r].tooltip(l);a.tooltip(l)}if(S&&(f.clipTop=f.clipTopPath,f.clipOuterFront=f.clipOuterFrontPath,f.clipOuterBack=f.clipOuterBackPath,a.attr({"clip-path":f.clipTop}),k.topBorder.attr({"clip-path":f.clipTop}),k.bottom.attr({"clip-path":f.clipTop}),k.bottomBorder.attr({"clip-path":f.clipTop}),k.frontOuter.attr({"clip-path":f.clipOuterFront}),k.backOuter.attr({"clip-path":f.clipOuterBack}),this.isDoughnut))f.clipInnerFront=
f.clipInnerFrontPath,f.clipInnerBack=f.clipInnerBackPath,k.frontInner.attr({"clip-path":f.clipInnerFront}),k.backInner.attr({"clip-path":f.clipInnerBack});a._confObject=f;f.thisElement=a;a._destroy=a.destroy;a.destroy=g;a._show=a.show;a.show=t;a._hide=a.hide;a.hide=e;a._on=a.on;a.on=c;a._attr=a.attr;a.attr=b;this.pointElemStore.push(a);return a}}()};T.prototype.constructor=T;k("renderer.pie3d",{type:"pie3d",translate:function(){var a=0,d=this.options,c=d.series[0],e=d.plotOptions.series.dataLabels,
t=d.plotOptions.pie3d,i=p(c.startAngle,0)%360,h=c.managedPieSliceDepth,f=c.slicedOffset=t.slicedOffset,g=this.canvasWidth,s=this.canvasHeight,j=[this.canvasLeft+g*0.5,this.canvasTop+s*0.5-h*0.5],k,m,l,n,r,d=c.data,E,K=ha(g,s),q,y,A,B=e.distance,J=c.pieYScale,z=c.pieSliceDepth,D=c.slicedOffsetY=f*J;j.push(t.size,t.innerSize||0);j=ea(j,function(a,c){return(q=/%$/.test(a))?[g,s-h,K,K][c]*parseInt(a,10)/100:a});j[2]/=2;j[3]/=2;j.push(j[2]*J);j.push((j[2]+j[3])/2);j.push(j[5]*J);c.getX=function(a,c){l=
F.asin((a-j[1])/(j[2]+B));return j[0]+(c?-1:1)*x(l)*(j[2]+B)};c.center=j;b(d,function(c){a+=c.y});c.labelsRadius=j[2]+B;c.labelsRadiusY=c.labelsRadius*J;c.quadrantHeight=(s-h)/2;c.quadrantWidth=g/2;n=-i*Z;n=I(n*1E3)/1E3;r=n+ba;t=o(parseInt(e.style.fontSize,10),10)+4;c.maxLabels=na(c.quadrantHeight/t);c.labelFontSize=t;c.connectorPadding=o(e.connectorPadding,5);c.isSmartLineSlanted=p(e.isSmartLineSlanted,!0);c.connectorWidth=o(e.connectorWidth,1);c.enableSmartLabels=e.enableSmartLabels;if(!c.pie3DManager)c.pie3DManager=
new T(j[0],j[1],j[2],j[3],J,z,this.layers.dataset,this.paper,c.data.length===1,c.use3DLighting);b(d,function(b){k=n;E=a?b.y/a:0;n=I((n+E*ba)*1E3)/1E3;n>r&&(n=r);m=n;b.shapeArgs={start:I(k*1E3)/1E3,end:I(m*1E3)/1E3};b.centerAngle=l=(m+k)/2%ba;b.slicedTranslation=[I(x(l)*f),I(V(l)*D)];y=x(l)*j[2];c.radiusY=A=V(l)*j[4];b.tooltipPos=[j[0]+y*0.7,j[1]+A];b.percentage=E*100;b.total=a})},drawPlotPie3d:function(a,b){this.translate();var c=this,e=a.items,d=a.data,g=c.options,h=g.plotOptions,f=h.series,i=c.layers,
k=c.elements.plots[0],j=c.datasets[0],h=h.series.dataLabels,l=f.dataLabels.style,f=o(a.moveDuration,f.animation.duration),m=c.paper,g=(g=g.tooltip||{})&&g.enabled!==!1,n,r=j.slicedOffset,p=j.slicedOffsetY,E=c.plotGraphicClick,K=c.plotDragMove,q=c.plotDragStart,y=c.plotDragEnd,F=c.plotMouseDown,A=c.plotMouseUp,I=!!c.datasets[0].enableRotation,z,D,G,B,J,P,H,R,U,L,M;if(!d||!d.length)d=[];k.singletonCase=d.length==1;k.chartPosition=Aa(c.container);k.pieCenter=j.center;k.timerThreshold=30;for(M=-1;++M<
d.length;)if(D=d[M],G=D.y,B=D.displayValue,P=D.sliced,L=D.shapeArgs,R=D.centerAngle,n=D.toolText,H=(J=!!D.link)||I||!D.doNotSlice,!(G===null||G===void 0))if(!(z=e[M])){b.data[M].plot=z=e[M]={chart:c,index:M,seriesData:k,value:G,angle:R,link:D.link,shapeArgs:L,slicedX:P&&!k.singletonCase?x(R)*r:0,slicedY:P&&!k.singletonCase?V(R)*p:0,sliced:P,labelText:B,graphic:j.pie3DManager.createSlice(L.start,L.end,D.color,D._3dAlpha,D.borderColor,D.borderWidth,M,g?n:"")};b.data[M].legendClick=function(a){return function(){c.legendClick(null,
c,a)}}(M);z.graphic.plotItem=z;z.transX=x(R)*r;z.transY=V(R)*p;z.slicedTranslation="t"+z.transX+","+z.transY;z.graphic.attr({transform:"t"+z.slicedX+","+z.slicedY,ishot:H,cursor:J?"pointer":""});if(!D.doNotSlice)z.graphic.on("click",function(a){return function(){E.call(a)}}(z));z.graphic.on("drag",function(a){return function(c,b,e,d,f){K.call(a,c,b,e,d,f)}}(z),function(a){return function(c,b,e){q.call(a,c,b,e)}}(z),function(a){return function(){y.call(a)}}(z));z.graphic.on("mousedown",function(a){return function(){F.call(a)}}(z));
z.graphic.on("mouseup",function(a){return function(){A.call(a)}}(z));if(B!==void 0&&(z.dataLabel=m.text(i.dataset).css(l).attr({text:B,title:D.originalText||"",fill:l.color||"#000000",visibility:"hidden",ishot:H,cursor:J?"pointer":""}),z.dataLabel.click(E,z),z.dataLabel.mousedown(F,z),z.dataLabel.mouseup(A,z),h.distance>0&&(U=h.connectorWidth)&&h.enableSmartLabels))z.connector=m.path("M 0 0 l 0 0",i.dataset).attr({"stroke-width":U,stroke:h.connectorColor||"#606060",visibility:"hidden",ishot:H,cursor:J?
"pointer":""}),z.connector.click(E,z),z.connector.mousedown(F,z),z.connector.mouseup(A,z)}j.pie3DManager.refreshDrawing();f>0?c.animate(e,f):c.placeDataLabels(!1,e)},rotate:function(a){var d=this.datasets[0],c=this.elements.plots[0].items,e=d.slicedOffset,g=d.slicedOffsetY,i=d.startAngle,h,a=a||-d._lastAngle;h=(a-i)%360;d.startAngle=o(a,d.startAngle)%360;h=-(h*M)/180;d.pie3DManager&&d.pie3DManager.rotate(h);b(c,function(a){var c=a.graphic,b=a.shapeArgs,b={start:b.start+=h,end:b.end+=h},d=a.angle=
wa((b.start+b.end)/2),b=a.sliced,i=x(d),d=V(d);a.slicedTranslation=[I(i*e),I(d*g)];a.transX=a.slicedTranslation[0];a.transY=a.slicedTranslation[1];a.slicedX=b?x(h)*e:0;a.slicedY=b?V(h)*g:0;c&&b&&a.graphic.attr({transform:"t"+a.slicedTranslation[0]+","+a.slicedTranslation[1]})});this.placeDataLabels(!0,c)},plotMouseDown:function(){this.seriesData.isRotating=!1},plotMouseUp:function(){var a=this.chart,b=this.seriesData;!b.isRotating&&a.linkClickFN.call({link:b.data[this.index].link},a);xa._supportsTouch&&
!b.isRotating&&a.plotGraphicClick.call(this)},plotDragStart:function(a,b,c){var e=this.seriesData,d=this.chart.datasets[0];if(d.enableRotation)a=Ca.call(c,a,b,e.pieCenter,e.chartPosition,d.pieYScale),d.dragStartAngle=a,d._lastAngle=-d.startAngle},plotDragEnd:function(){var a=this.chart;ia(a.logic.chartInstance.jsVars._reflowData,{hcJSON:{series:[{startAngle:a.datasets[0].startAngle}]}},!0)},plotDragMove:function(a,b,c,e,d){var g=this.chart,a=g.datasets[0],b=this.seriesData;if(g.options.series[0].enableRotation&&
!b.singletonCase&&(b.isRotating=!0,c=Ca.call(d,c,e,b.pieCenter,b.chartPosition,a.pieYScale),e=c-a.dragStartAngle,a.dragStartAngle=c,b.moveDuration=0,a._lastAngle+=e*180/M,c=(new Date).getTime(),!a._lastTime||a._lastTime+b.timerThreshold<c))a._lastTime||g.rotate(),b.timerId=setTimeout(function(){g.rotate()},b.timerThreshold),a._lastTime=c},animate:function(a,b){var c,e,d,g=a.length,h,f,i,k=this,j;for(c=0;c<g;c++)if(h=a[c],f=h.graphic,i=h.shapeArgs,h=2*M,f)f.attr({start:h,end:h}),j=i.start,i=i.end,
e?f.animateWith(e,d,{cx:j-h,cy:i-h},b,"ease-in"):(d=xa.animation({cx:j-h,cy:i-h},b,"ease-in",function(){k.placeDataLabels(!1,a)}),e=f.animate(d))},plotGraphicClick:function(){var a=this.seriesData,b=this.chart,c,e,d,g,h,f;if(!a.isRotating&&!a.singletonCase)return c=this.graphic,e=this.connector,d=this.dataLabel,a=this.sliced,g=this.connectorPath,h=(a?-1:1)*this.transX,f=(a?-1:1)*this.transY,c.animate({transform:a?"t0,0":"t"+h+","+f},200,"easeIn"),d&&d.x&&d.animate({x:d.x+(a?0:h)},200,"easeIn"),g&&
(g[1]+=h,g[2]+=f,g[4]+=h,g[6]+=h,e.animate({path:g},200,"easeIn")),a=this.sliced=!a,c={hcJSON:{series:[]}},c.hcJSON.series[0]={data:[]},ia(b.logic.chartInstance.jsVars._reflowData,c,!0),a},placeDataLabels:function(){var a=function(a,b){return a.point.value-b.point.value},d=function(a,b){return a.angle-b.angle},c=["start","start","end","end"],e=[-1,1,1,-1],i=[1,1,-1,-1];return function(k,h){var f=this.datasets[0],l=this.smartLabel,s=this.options.plotOptions.series.dataLabels,j=s.style,w=o(parseInt(j.lineHeight,
10),12),m=qa(s.placeInside,!1),r=s.skipOverlapLabels,E=s.manageLabelOverflow,p=s.connectorPadding,A=s.distance;qa(s.softConnector,!0);var I=s.connectorWidth,q,y,A=A>0,B=f.center,J=B[1],M=B[0],z=B[2],D=B[4],G=[[],[],[],[]],P,U,C,H=this.canvasLeft,R=this.canvasTop,Z=this.canvasWidth,L,O,Q,N,ga,S,W,T,na,za,ja,ea=f.labelsRadius,Y=f.labelsRadiusY,ma=f.labelFontSize,ca=ma,fa=ca/2,p=[p,p,-p,-p],ia=f.maxLabels,la=f.isSmartLineSlanted,pa=f.enableSmartLabels,ka,f=f.pieSliceDepth/2;k||l.setStyle(j);if(h.length==
1){if(N=h[0],ka=N.dataLabel,N.slicedTranslation=[H,R],ka)ka.attr({visibility:n,"text-anchor":"middle",x:M,y:J+fa-2}),ka.x=M}else if(m)b(h,function(a){if(ka=a.dataLabel){ja=a.angle;za=J+B[6]*V(ja)+fa-2;W=M+B[5]*x(ja);ka.x=W;ka._x=W;ka.y=za;if(a.sliced){var a=a.slicedTranslation,b=a[1]-R;W+=a[0]-H;za+=b}ka.attr({visibility:n,align:"middle",x:W,y:za})}});else{b(h,function(a){if(ka=a.dataLabel)ja=a.angle,ja<0&&(ja=ba+ja),P=ja>=0&&ja<oa?1:ja<X?2:ja<Qa?3:0,G[P].push({point:a,angle:ja})});for(C=m=4;C--;){if(r&&
(N=G[C].length-ia,N>0)){G[C].sort(a);U=G[C].splice(0,N);O=0;for(Q=U.length;O<Q;O+=1)N=U[O].point,N.dataLabel.attr({visibility:"hidden"}),N.connector&&N.connector.attr({visibility:"hidden"})}G[C].sort(d)}C=Pa(G[0].length,G[1].length,G[2].length,G[3].length);Y=Pa(ha(C,ia)*ca,Y);G[1].reverse();G[3].reverse();for(l.setStyle(j);m--;){O=G[m];Q=O.length;r||(ca=Q>ia?Y/Q:ma,fa=ca/2);N=Q*ca-fa;j=Y+fa;for(C=0;C<Q;C+=1,N-=ca)y=aa(Y*V(O[C].angle)),j-y<ca?y=j-ca:y<N&&(y=N),j=O[C].oriY=y;U=c[m];Q=Y-Q*ca+fa;j=-fa;
for(C=O.length-1;C>=0;C-=1,Q+=ca){N=O[C].point;ja=O[C].angle;ga=N.sliced;ka=N.dataLabel;y=aa(Y*V(ja));y-j<ca?y=j+ca:y>Q&&(y=Q);j=y;T=(y+O[C].oriY)/2;y=M+i[m]*ea*x(F.asin(T/Y));T*=e[m];T+=J;na=J+D*V(ja);S=M+z*x(ja);W=y+p[m];za=T+fa-2;q=W+p[m];ka.x=q;ka._x=q;E&&(L=m>1?q-this.canvasLeft:this.canvasLeft+Z-q,L=l.getSmartText(N.labelText,L,w),ka.attr({text:L.text,title:L.tooltext||""}));ja<X&&(T+=f,na+=f,za+=f);ka.y=za;if(ga)ga=N.transX,L=N.transY,W+=ga,y+=ga,S+=ga,na+=L,q+=ga;ka.attr({visibility:n,"text-anchor":U,
x:q,y:T});if(A&&I&&pa)q=N.connector,N.connectorPath=y=[g,S,na,K,la?y:S,T,W,T],q?(q.attr({path:y}),q.attr("visibility",n)):N.connector=q=this.paper.path(y).attr({"stroke-width":I,stroke:s.connectorColor||"#606060",visibility:n})}}}}}(),legendClick:function(a,b,c){a=b.elements.plots[0];a.isRotating=!1;b.plotGraphicClick.call(a.items[c])}},k["renderer.root"]);k("renderer.pie",{drawPlotPie:function(a,b){var c=this,e=a.items,d=a.data,g=c.options,h=g.plotOptions,f=h.pie,i=h.series,k=c.layers,j=k.dataset,
l=c.elements.plots[0],h=h.series.dataLabels,m=i.dataLabels.style,r=i.shadow,i=o(a.moveDuration,i.animation.duration),p=c.paper,g=(g=g.tooltip||{})&&g.enabled!==!1,E=(b.startAngle||0)%ba,F=f.slicedOffset,K=ba/b.valueTotal,q=c.canvasLeft+c.canvasWidth*0.5,y=c.canvasTop+c.canvasHeight*0.5,A=f.size*0.5,B=(f.innerSize||0)*0.5,I=c.plotGraphicClick,z=c.plotDragMove,D=c.plotDragStart,G=c.plotDragEnd,J=c.plotMouseDown,C=c.plotMouseUp,M=!!c.datasets[0].enableRotation,H,U,P,L,X,O,N,ha,Z,W,T,S=a.shadowGroup,
aa,ca,Y;if(!d||!d.length)d=[];if(!S)S=a.shadowGroup=p.group(j).toBack();l.singletonCase=d.length==1;l.chartPosition||(l.chartPosition=Aa(c.container));l.pieCenter=[q,y];l.timerThreshold=30;W=Z=E;for(aa=d.length;aa--;)if(U=d[aa],P=U.y,L=U.displayValue,O=U.sliced,f=U.toolText,N=(X=!!U.link)||M||!U.doNotSlice,!(P===null||P===void 0)){H=U.color.FCcolor;H.r=A;H.cx=q;H.cy=y;W=Z;Z-=P*K;ha=(Z+W)*0.5;if(!(H=e[aa]))if(b.data[aa].plot=H=e[aa]={chart:c,index:aa,seriesData:l,value:P,angle:ha,slicedX:x(ha)*F,slicedY:V(ha)*
F,sliced:O,labelText:L,graphic:p.ringpath(q,y,A,B,E,E,k.dataset).attr({"stroke-width":U.borderWidth,stroke:U.borderColor,fill:Q(U.color),"stroke-dasharray":U.dashStyle,redrawDataLabels:E,ishot:N,cursor:X?"pointer":""}).shadow(r&&U.shadow,S).drag(z,D,G).mousedown(J).mouseup(C)},U.doNotSlice||H.graphic.click(I),g&&H.graphic.tooltip(f),b.data[aa].legendClick=function(a){return function(){c.legendClick(null,c,a)}}(aa),H.graphic.data("plotItem",H),L!==void 0&&(H.dataLabel=p.text(j).css(m).attr({text:L,
fill:m.color||"#000000",ishot:N}).click(I).drag(z,D,G).mousedown(J).mouseup(C).hide(),H.dataLabel.data("plotItem",H),h.distance>0&&(T=h.connectorWidth)&&h.enableSmartLabels))H.connector=p.path("M 0 0 l 0 0",j).attr({"stroke-width":T,stroke:h.connectorColor||"#606060",visibility:n,ishot:!0}).click(I).drag(z,D,G).mousedown(J).mouseup(C),H.connector.data("plotItem",H);H.angle=ha;H.transX=x(ha)*F;H.transY=V(ha)*F;H.slicedTranslation="t"+x(ha)*F+","+V(ha)*F;ca?H.graphic.animateWith(ca,Y,{ringpath:[q,y,
A,B,Z,W],transform:H.sliced?H.slicedTranslation:""},i,"easeIn"):(Y=xa.animation({ringpath:[q,y,A,B,Z,W],redrawDataLabels:c,transform:H.sliced?H.slicedTranslation:""},i,"easeIn",function(){if(!c.paper.ca.redrawDataLabels)c.placeDataLabels(!1,e,a),c.paper.ca.redrawDataLabels=c.redrawDataLabels}),ca=H.graphic.animate(Y))}},rotate:function(a,b){var c=a.items,d=a.data,g=this.options.plotOptions.pie,i=g.slicedOffset,h=ba/b.valueTotal,f=this.canvasLeft+this.canvasWidth*0.5,k=this.canvasTop+this.canvasHeight*
0.5,l=g.size*0.5,g=(g.innerSize||0)*0.5,j,n,m,r,p;r=(b.startAngle||0)%ba;for(p=d.length;p--;)if(n=d[p],j=n.y,!(j===null||j===void 0))n=r,r-=j*h,m=(r+n)*0.5,j=c[p],j.angle=m,j.transX=x(m)*i,j.transY=V(m)*i,j.slicedTranslation="t"+x(m)*i+","+V(m)*i,j.graphic.attr({ringpath:[f,k,l,g,r,n],transform:j.sliced?j.slicedTranslation:""});this.placeDataLabels(!0,c,a)}},k["renderer.piebase"])},[3,2,2,"sr4"]]);
FusionCharts(["private","modules.renderer.js-zoomline",function(){var Aa=this,ea=Aa.hcLib,wa=ea.chartAPI,Ba=ea.chartAPI,la=ea.extend2,Ca=ea.raiseEvent,T=ea.pluck,A=ea.pluckNumber,B=ea.getFirstColor,xa=ea.graphics.convertColor,Ea=ea.defaultPaletteOptions,C=ea.bindSelectionEvent,Ma=ea.createTrendLine,p=ea.Raphael,fa=ea.FC_CONFIG_STRING,o="rgba(192,192,192,"+(p.svg?1.0E-6:0.0020)+")",O=Math,qa=O.ceil,ya=O.floor,ra=O.max,Y=O.min,ia=O.cos,sa=O.sin,Q=parseFloat,Fa=parseInt,Ja=function(b){return b&&b.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,
"\\$&")},S;la(ea.eventList,{zoomed:"FC_Zoomed",pinned:"FC_Pinned",resetzoomchart:"FC_ResetZoomChart"});wa("zoomline",{rendererId:"zoomline",standaloneInit:!0,hasVDivLine:!0,defaultSeriesType:"stepzoom",canvasborderthickness:1,defaultPlotShadow:1,chart:function(){var b=this.base.chart.apply(this,arguments),d=this.dataObj.chart,l=Ea.canvasBorderColor[this.paletteIndex],i=b.chart;la(i,{animation:!1,zoomType:"x",canvasPadding:A(d.canvaspadding,0),scrollColor:B(T(d.scrollcolor,Ea.altHGridColor[i.paletteIndex])),
scrollBtnWidth:A(d.scrollbtnwidth,d.scrollheight,16),scrollHeight:A(d.scrollheight,16)||16,allowPinMode:A(d.allowpinmode,1),skipOverlapPoints:A(d.skipoverlappoints,1),showToolBarButtonTooltext:A(d.showtoolbarbuttontooltext,1),btnResetChartTooltext:T(d.btnresetcharttooltext,"Reset Zoom"),btnZoomOutTooltext:T(d.btnzoomouttooltext,"Zoom out one level"),btnSwitchToZoomModeTooltext:T(d.btnswitchtozoommodetooltext,"Select a subset of data to zoom into it for detailed view"),btnSwitchToPinModeTooltext:T(d.btnswitchtopinmodetooltext,
"Switch to Pin Mode"),pinPaneFill:xa(T(d.pinpanebgcolor,l),A(d.pinpanebgalpha,15)),zoomPaneFill:xa(T(d.zoompanebgcolor,"#b9d5f1"),A(d.zoompanebgalpha,30)),zoomPaneStroke:xa(T(d.zoompanebordercolor,"#3399ff"),A(d.zoompaneborderalpha,80))});return b},preSeriesAddition:function(){var b=this.dataObj,d=b.chart,l=(l=b.categories)&&l[0]||{},i=l.category,b=this.hcJSON,n=b[fa],g=this.smartLabel,p=A(d.compactdatamode,0),E=T(d.dataseparator,"|"),r=A(d.showlabels,1),F=r&&A(d.labelheight),o=d.labeldisplay&&d.labeldisplay.toLowerCase()===
"rotate"?270:A(d.rotatelabels,1)?270:0,x=b.xAxis.labels.style,B=Q(x.lineHeight),I=b.chart.labelPadding=A(d.labelpadding,2)+b.chart.plotBorderWidth,C,O;delete l.category;b.categories=C=la({data:E=p&&i&&i.split&&i.split(E)||i||[],rotate:o},l);i!==void 0&&(l.category=i);l=E.length||0;for(i=!p&&r&&F!==0&&l||0;i--;)E[i]=E[i]&&(O=E[i].label)||"";p&&l&&(O=E[0]);F===void 0&&r&&(O?(g.setStyle(x),O=g.getSmartText(O),F=o?O.width:O.height):F=B*(o&&3||1));F>n.height*0.5&&(F=n.height*0.5);C.labelHeight=F&&F+5||
0;C.show=F&&r||0;C.css=la({},x);o?(C.css.rotation=o,C.css["text-anchor"]="end"):C.css["vertical-align"]="top";b.xAxis.min=0;b.xAxis.max=l&&l-1||0;F+=A(d.scrollheight,16)||16;b.chart.marginBottom+=I;n.marginBottomExtraSpace+=F;T(d.caption,d.subcaption)||(n.marginTopExtraSpace+=16)},series:function(){var b=this.dataObj,d=b.chart,l=b.dataset,i=this.hcJSON,n=i[fa],g=n[0],p=i.series,E=A(d.yaxismaxvalue),r=A(d.yaxisminvalue),o=A(d.forceyaxislimits,0),B=A(d.compactdatamode,0),x=T(d.dataseparator,"|"),C=
Ja(d.indecimalseparator),I=Ja(d.inthousandseparator),O=A(d.drawanchors,d.showanchors,1),S=!!A(d.showlegend,1),aa,M,na,P,Z,X=Infinity,oa=-Infinity,ba;Z=i.categories.data.length;if(l&&l.length&&Z){C&&(C=RegExp(C,"g"));I&&(I=RegExp(I,"g"));!I&&!C&&B&&o&&E!==void 0&&r!==void 0?(o=!0,oa=ra(E,r),X=Y(r,E)):o=!1;E=0;for(r=l.length;E<r;E++){aa=l[E];na=aa.data;delete aa.data;B?(P=na||"",I&&(P=P.replace(I,"")),C&&(P=P.replace(C,".")),P=P.split(x)):P=na||[];if(P.length>Z)P.length=Z;ba=P.length;if(B){if(!o)for(;ba--;)M=
Q(P[ba]),isNaN(M)&&(M=void 0),M>oa&&(oa=M),M<=X&&(X=M),P[ba]=M}else for(;ba--;)M=P[ba]&&P[ba].value||"",I&&(M=M.replace(I,"")),C&&(M=M.replace(C,".")),M=Q(M),isNaN(M)&&(M=void 0),M>oa&&(oa=M),M<=X&&(X=M),P[ba]=M;p.push(M={index:E,type:"zoomline",data:P,name:aa.seriesname||"",showInLegend:aa.seriesname&&A(aa.includeinlegend,1)&&S||!1,showAnchors:A(aa.drawanchors,aa.showanchors,O),visible:!!A(aa.initiallyvisible,1),lineWidth:2});P.length=Z;na!==void 0&&(aa.data=na);M.attrs=this.seriesGraphicsAttrs(aa,
E);aa=M.attrs.anchors;M.color=M.attrs.graphics.stroke;M.ancorRadius=aa.r+aa["stroke-width"]/2;M.marker={fillColor:aa.fill,lineColor:aa.stroke,lineWidth:1,symbol:"circle"}}(oa===-Infinity||X===Infinity)&&(oa=X=void 0);o=Fa(A(d.displaystartindex,1),10)-1;x=Fa(A(d.displayendindex,Z||2),10)-1;(l=A(d.pixelsperpoint,15))<15&&(l=15);(p=A(d.pixelsperlabel,i.categories.rotate?20:60))<l&&(p=l);(o<0||o>=(Z-1||1))&&(o=0);(x<=o||x>(Z-1||1))&&(x=Z-1||1);i.stepZoom={cnd:A(d.connectnulldata,0),amrd:A(d.anchorminrenderdistance,
20),nvl:A(d.numvisiblelabels,0),cdm:B,oppp:l,oppl:p,dsi:o,dei:x,vdl:x-o,dmax:g.max=oa,dmin:g.min=X,clen:Z,offset:0,step:1,llen:0,alen:0,ddsi:o,ddei:x};i.crossline={style:{lineHeight:n.inCanvasStyle.lineHeight,fontSize:n.inCanvasStyle.fontSize,fontFamily:n.inCanvasStyle.fontFamily}};this.configureAxis(i,b);b.trendlines&&Ma(b.trendlines,i.yAxis,n,!1,this.isBar)}},seriesGraphicsAttrs:function(b,d){var l=this.dataObj.chart,i=this.hcJSON.colors,n=(b.dashed||l.linedashed||"0")!=0,g,i={"stroke-width":A(b.linethickness,
l.linethickness,2),stroke:B(T(b.color,l.linecolor,i[d%i.length])),"stroke-opacity":A(b.alpha,l.linealpha,100)/100,"stroke-dasharray":n?[A(b.linedashlen,l.linedashlen,5),A(b.linedashgap,l.linedashgap,4)]:"none","stroke-linejoin":"round","stroke-linecap":"round"},n=la({},i);g=i["stroke-width"]+A(l.pinlinethicknessdelta,1);n["stroke-width"]=g>0&&g||0;n["stroke-dasharray"]=[3,2];return{graphics:i,pin:n,shadow:{opacity:i["stroke-opacity"],apply:A(l.showshadow,+!p.vml)},anchors:{"stroke-linejoin":"round",
"stroke-linecap":"round",r:A(b.anchorradius,l.anchorradius,i["stroke-width"]+2),stroke:B(T(b.anchorbordercolor,l.anchorbordercolor,i.stroke)),"stroke-opacity":A(b.anchorborderalpha,l.anchorborderalpha,100)/100,"stroke-width":A(b.anchorborderthickness,l.anchorborderthickness,i["stroke-width"]),fill:B(T(b.anchorbgcolor,l.anchorbgcolor,"#ffffff")),"fill-opacity":A(b.anchorbgalpha,l.anchorbgalpha,100)/100,opacity:A(b.anchoralpha,l.anchoralpha,100)/100}}}},wa.msline);Ba("renderer.zoomline",{resetZoom:function(){var b=
this._zoomhistory,d=this.options.stepZoom;if(!b.length)return!1;b.length=0;this.zoomTo(d.dsi,d.dei)&&Ca("resetzoomchart",this._zoomargs,this.fusionCharts,[this.fusionCharts.id]);return!0},zoomOut:function(){var b=this._zoomhistory.pop(),d=this.options.stepZoom,l,i,n;b?(l=b.dsi,i=b.dei):this._prezoomed&&(l=0,i=d.clen-1);(n=this.zoomTo(l,i))&&Aa.raiseEvent("zoomedout",n,this.fusionCharts);return!0},zoomRange:function(b,d){var l=this._zoomhistory,i=this._zoominfo,n=i.ppp,i=i.ddsi,g;l.push(this._zoominfo);
(g=this.zoomTo(i+ya(b/n),i+ya(d/n)))?Aa.raiseEvent("zoomedin",g,this.fusionCharts):l.pop()},zoomTo:function(b,d){var l=this.xlabels.data,i=this._zoominfo,n=this._zoomhistory,g=i.clen;b<0&&(b=0);b>=g-1&&(b=g-1);d<=b&&(d=b+1);d>g-1&&(d=g-1);if(b===d||b===i.dsi&&d===i.dei)return!1;this.pinRange();i=la({},i);i.dsi=b;i.dei=d;i=this._zoominfo=i;this.updatePlotZoomline();this.zoomOutButton[i.vdl===i.clen-1?"hide":"show"]();this.resetButton[n.length?"show":"hide"]();this.elements.zoomscroller.attr({"scroll-ratio":i.vdl/
(g-!!g),"scroll-position":[i.dsi/(g-i.vdl-1),!0]});l={level:n.length+1,startIndex:b,startLabel:l[b],endIndex:d,endLabel:l[d]};Ca("zoomed",l,this.fusionCharts,[this.fusionCharts.id,b,d,l.startLabel,l.endLabel,l.level]);return l},pinRange:function(b,d){var l=this.paper,i=this.elements,n=this.xlabels.data,g=this._zoominfo,p=this.layers.zoompin,o=i.pinrect,i=i["clip-pinrect"],r=this.plots,F=d-b,B,x;if(g&&p&&o){if(b===d)return p.hide(),this.pinButton.attr("button-active",!1),g.pinned=!1;for(x=r.length;x--;){o=
r[x];B=o.pinline;if(!B)B=o.pinline=l.path(void 0,p).attr(o.attrPin);B.attr("path",o.graphic.attrs.path)}i[0]=b;i[2]=F;p.attr({transform:["T",this._visx,this._yzero],"clip-rect":i}).show();b=this.getValuePixel(b);d=this.getValuePixel(d);Ca("pinned",{startIndex:b,endIndex:d,startLabel:n[b],endLabel:n[d]},this.fusionCharts,[this.fusionCharts.id,b,d,n[b],n[d]]);return g.pinned=!0}},getValuePixel:function(b){var d=this._zoominfo;return d.ddsi+ya(b/d.ppp)},drawGraph:function(){var b=this,d=b.paper,l=b.canvasLeft,
i=b.canvasTop,n=b.canvasWidth,g=b.canvasHeight,o=b.options,E=o.chart,r=E.plotBorderWidth,F=E.showToolBarButtonTooltext,B=b.layers,x=b.toolbar,A=b.elements,I=E.allowPinMode,O=o.categories,Q=!1,aa,M,T,P;P=b._zoominfo=la({},o.stepZoom);b._zoomhistory=[];if(P.clen){Q=b._prezoomed=P.dei-P.dsi<P.clen-1;b._visw=b.canvasWidth-E.canvasPadding*2;T=b._visx=b.canvasLeft+E.canvasPadding;b._visout=-(b.chartHeight+b.canvasHeight+1E3);b.base.drawGraph.apply(b,arguments);b._ypvr=b.yAxis[0]&&b.yAxis[0].pixelValueRatio||
0;o=b._yzero||0;aa=B.dataset.attr("clip-rect",[b._visx,b.canvasTop,b._visw,b.canvasHeight]);M=B.scroll||(B.scroll=d.group("scroll").insertAfter(B.layerAboveDataset));b.xlabels=[];b.xlabels.show=O.show;b.xlabels.rotate=O.rotate;b.xlabels.data=O.data||[];b.xlabels.css=O.css;b.xlabels.group=d.group("zoomline-plot-xlabels",B.datalabels);B.datalabels.transform(["T",T,i+g+E.scrollHeight+E.labelPadding]);b._lcmd=O.rotate?"y":"x";if(I)I=p.crispBound(0,i-o,0,g,r),A["clip-pinrect"]=[I.x,I.y-1,I.width,I.height],
B.zoompin=d.group("zoompin").insertBefore(aa).transform(["T",T,o]).hide(),A.pinrect=d.rect(0,i-o,b._visw,g,B.zoompin).attr({"stroke-width":0,stroke:"none",fill:E.pinPaneFill,"shape-rendering":"crisp",ishot:!0,cursor:"w-resize"}).drag(function(){},function(){}),b.pinButton=x.add("pinModeIcon",function(){var d=b._zoominfo,g=b.pinButton;d.pinned?(b.pinRange(),F&&g.tooltip(E.btnSwitchToPinModeTooltext||"")):(d.pinned=!0,F&&g.tooltip(E.btnSwitchToZoomModeTooltext||""));g.attr("button-active",d.pinned)},
{tooltip:F&&E.btnSwitchToPinModeTooltext||""});I=p.crispBound(l-r,i+g+r,n+r+r,E.scrollHeight,r);A.zoomscroller=d.scroller(I.x,I.y,I.width,I.height,!0,{showButtons:!0,scrollRatio:P.vdl/(P.clen-!!P.clen),scrollPosition:[P.dsi/(P.clen-P.vdl-1),!1]},M).attr("fill",E.scrollColor).scroll(b.updatePlotZoomline,b);C(b,function(d){var g=d.selectionLeft-l,d=g+d.selectionWidth;b.crossline&&b.crossline.hide();b[b._zoominfo.pinned?"pinRange":"zoomRange"](g,d)},{attr:{stroke:E.zoomPaneStroke,fill:E.zoomPaneFill,
strokeWidth:0}});b.zoomOutButton=x.add("zoomOutIcon",function(){b.zoomOut()},{tooltip:F&&E.btnZoomOutTooltext||""})[Q&&"show"||"hide"]();b.resetButton=x.add("resetIcon",function(){b.resetZoom()},{tooltip:F&&E.btnResetChartTooltext||""}).hide();I=b.resetButton.attr("fill");I[2]="rgba(255,255,255,0)";b.resetButton.attr("fill",[I[0],I[1],I[2],I[3]]);b.crossline=new S(b);b.updatePlotZoomline()}},drawPlotZoomline:function(b,d){var l=this.paper,i=this._yzero||(this._yzero=this.yAxis[0].getAxisPosition(0)),
n=d.attrs,g=d.visible,p=g?"show":"hide",o=this.layers.dataset,r=b.group||(b.group=l.group("plot-zoomline-dataset",o)),o=b.anchorGroup||(b.anchorGroup=l.group("plot-zoomline-anchors",o)),l=b.graphic||(b.graphic=l.path(void 0,r)),i=["T",this._visx,i];r.transform(i)[p]();o.transform(i)[p]();b.graphic=l.attr(n.graphics).shadow(n.shadow);b.attrPin=n.pin;b.visible=g;b.anchors=[];b.anchors.show=d.showAnchors;b.anchors.attrs=n.anchors;b.anchors.left=-(n.anchors.r+n.anchors["stroke-width"]*0.5);b.anchors.right=
this._visw-b.anchors.right},updatePlotZoomline:function(b,d){var l=this.paper,i=this._ypvr,n=this._visw,g=this.xlabels,p=g.css,o=g.group,r=this.plots,B,A,x,C,I,O;!d&&(d=this._zoominfo);A=d.oppp;x=d.vdl=d.dei-d.dsi;d.ppl=d.oppl;C=d.ppl=d.nvl?n/d.nvl:d.oppl;n=d.step=(I=d.ppp=n/x)<A?qa(A/I):1;A=d.lskip=qa(C/I/n);b!==void 0?(C=(d.clen-x-1)*b,d.offset=(C-(C=Fa(C)))*I,O=C+x):(C=d.dsi,O=d.dei,d.offset=0);x=d.norm=C%n;d.ddsi=C-=x;d.ddei=O=O+2*n-x;d.pvr=i;i=g.show?qa((O-C)/n/A):0;A=d.llen-1;d.llen=i;if(i>
A){x=A;for(A=i;x<A;x++)(B=g[x])&&B.show()||(g[x]=l.text(0,0,"",o).css(p))}else{x=i;for(A+=1;x<A;x++)g[x].hide()}i=I*n<d.amrd?0:qa((O-C)/n);I=i-d.alen;d.alen=i;for(n=r.length;n--;){p=r[n];o=p.anchors;if(o.show&&I){B=o.attrs;x=0;for(A=i;x<A;x++)o[x]=o[x]&&o[x].show()||l.circle(0,0,0,p.anchorGroup).attr(B);x=i;for(A=o.length;x<A;x++)o[x]&&o[x].hide()}this.drawPlotZoomlineGraphics(d,p.data,p.graphic,o,!n&&g)}if(window.FC_DEV_ENVIRONMENT)FusionCharts.debugMode.enabled()?(this.debug=this.debug||($("#fc-zoominfo").length||
$("body").append('<pre id="fc-zoominfo">'),$("#fc-zoominfo").css({position:"absolute",left:"10px",top:"0","pointer-events":"none",opacity:0.7,width:"250px",zIndex:"999",border:"1px solid #cccccc","box-shadow":"1px 1px 3px #cccccc",background:"#ffffff"})),this.debug.text(JSON.stringify(d,0,2))):($("#fc-zoominfo").remove(),delete this.debug)},drawPlotZoomlineGraphics:function(b,d,l,i,n){var g=[],p=b.cnd,o=b.ddei,r=b.clen,B=b.step,A=b.lskip,x=b.ppp,C=b.offset,I=b.pvr,O=this._visw,Q=this._visout,T=this._lcmd,
M="M",S,P,Z=n&&n[0],X=Z&&n.data,i=i[0],Y={},ba={},fa,ea=0,W,ia=-b.norm,b=b.ddsi,la=0;for(Z&&n.group.transform(["T",-C,0]);b<=o;b+=B,ia+=B)if(W=ea/3+la,fa=ia*x,(S=d[b])===void 0?(!p&&(M="M"),P=Q,n=fa-C,S=Q,la++):(g[ea++]=M,g[ea++]=P=n=fa-C,g[ea++]=S*=I,M="L"),i&&(i=i.attr((Y.cx=P,Y.cy=S,Y)).next),Z&&!(W%A))W=Z.attrs,P=X[b]||"",n=n<0||n>O?Q:fa,W.text===P?delete ba.text:ba.text=P,W[T]===n?delete ba[T]:ba[T]=n,Z=Z.attr(ba).next;if(o>=r){if((S=d[r-1])!==void 0)ia-=o-r,g[ea++]="L",g[ea++]=ia*x-C,g[ea++]=
S*I;i&&i.attr((Y.cx=Q,Y.cy=Q,Y))}l.attr("path",g)},legendClick:function(b){var d=!b.visible,l=d?"show":"hide";b.group[l]();b.anchorGroup[l]();this.base.legendClick.apply(this,arguments);return b.visible=d}},Ba["renderer.cartesian"]);S=function(b){var d=b.paper,l=this.left=b._visx,i=this.width=b._visw,n=b.canvasTop,g=b.canvasHeight,p=b._visout,B=this.plots=b.plots,r=b.layers.dataset,A=this.group=d.group("crossline-labels",r).attr({transform:["T",l,b._yzero]});this.tracker=d.rect(l,n,i,g,r).attr({stroke:"none",
"stroke-width":0,fill:o}).toFront().mousedown(this.onMouseDown,this).mouseup(this.onMouseUp,this,!0).mouseout(this.onMouseOut,this).mousemove(this.onMouseMove,this);this.line=d.path(void 0,r).attr({path:["M",l,n,"l",0,g],"stroke-opacity":0.2}).toBack();l=this.labels=d.set();i=b.options.crossline.style;this.hide();this.pixelRatio=b._ypvr;this.getZoomInfo=function(){return b._zoominfo};this.getDataIndexFromPixel=function(d){return b.getValuePixel(d)};n=0;for(g=B.length;n<g;n++)r=B[n],r=r.graphic.attrs.stroke,
l.push(d.text(0,p,"",A).css(i).attr({fill:r,"text-bound":["rgba(255,255,255,0.8)","rgba(0,0,0,0.2)",1,2]}))};S.prototype.onMouseOut=function(){this.hide()};S.prototype.onMouseDown=function(){this.hide();this._mouseIsDown=!0};S.prototype.onMouseUp=function(){this.hide();delete this._mouseIsDown};S.prototype.onMouseMove=function(b){if(!this._mouseIsDown){var d=this.getZoomInfo(),l=this.line,i=d.step,n=d.ppp*i,b=(b.layerX||b.x)-this.left,g,b=(b+=n/2+d.offset)-b%n;g=(g=this.getDataIndexFromPixel(b))+
g%i;b-=d.offset;l.transform(["T",ya(b),0]);if(g!==this.position||this.hidden)this.position=g,this.lineX=b,this.updateLabels();this.hidden&&this.show()}};S.prototype.updateLabels=function(){var b=this.plots,d=this.width,l=this.position,i=this.lineX,n=this.pixelRatio,g;this.labels.forEach(function(p,o){g=b[o].data[l];p.attr({text:g+"",x:ya(i),y:g===void 0?-1E3:g*n,"text-anchor":i<=0&&"start"||i>=d&&"end"||"middle"})})};S.prototype.show=function(){this.hidden=!1;this.group.show();this.line.show()};S.prototype.hide=
function(){this.hidden=!0;this.group.hide();this.line.hide()};p.addSymbol({pinModeIcon:function(b,d,l){var i=l*0.5,n=b-l,g=b+l,p=b-i,o=b+i,r=b+0.5,B=r+1,A=r+1.5,x=d-l,C=d+i,I=d-i,i=d+(l-i);return["M",n,x,"L",p,I,p,i,n,C,b-0.5,C,b,d+l+0.5,r,C,g,C,o,i,o,I,g,x,A,x,A,I,A,i,B,i,B,I,A,I,A,x,"Z"]},zoomOutIcon:function(b,d,l){b-=l*0.2;d-=l*0.2;var i=l*0.8,n=p.rad(43),g=p.rad(48),o=b+i*ia(n),n=d+i*sa(n),A=b+i*ia(g),g=d+i*sa(g),r=p.rad(45),B=o+l*ia(r),C=n+l*sa(r),x=A+l*ia(r),l=g+l*sa(r);return["M",o,n,"A",
i,i,0,1,0,A,g,"Z","M",o+1,n+1,"L",B,C,x,l,A+1,g+1,"Z","M",b-2,d,"L",b+2,d,"Z"]},resetIcon:function(b,d,l){var i=b-l,n=(O.PI/2+O.PI)/2;b+=l*ia(n);var n=d+l*sa(n),g=l*2/3;return["M",i,d,"A",l,l,0,1,1,b,n,"L",b+g,n-1,b+2,n+g-0.5,b,n]}})}]);